UPDATE `items` SET `desc` = 'A corrosive substance used for various purposes.'  WHERE `id` = 	1	;
UPDATE `items` SET `desc` = 'A flowering plant found in the wild known for its medicinal properties.'  WHERE `id` = 	2	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow Agarita plants.'  WHERE `id` = 	3	;
UPDATE `items` SET `desc` = 'A type of ginseng native to the Alaskan region prized for its healing properties.'  WHERE `id` = 	4	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow Alaskan Ginseng.'  WHERE `id` = 	5	;
UPDATE `items` SET `desc` = 'An intoxicating beverage consumed for recreational purposes.'  WHERE `id` = 	6	;
UPDATE `items` SET `desc` = 'Raw meat obtained from hunting alligators suitable for cooking.'  WHERE `id` = 	568	;
UPDATE `items` SET `desc` = 'The skin of an alligator commonly used for crafting and trading.'  WHERE `id` = 	544	;
UPDATE `items` SET `desc` = 'A tooth extracted from an alligator sometimes used for decorative purposes.'  WHERE `id` = 	543	;
UPDATE `items` SET `desc` = 'A species of ginseng native to North America valued for its medicinal properties.'  WHERE `id` = 	7	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow American Ginseng.'  WHERE `id` = 	8	;
UPDATE `items` SET `desc` = 'A standard arrow used with bows for hunting and combat.'  WHERE `id` = 	1238	;
UPDATE `items` SET `desc` = 'An explosive arrow designed to cause significant damage upon impact.'  WHERE `id` = 	10	;
UPDATE `items` SET `desc` = 'An arrow equipped with a flaming tip capable of setting targets on fire.'  WHERE `id` = 	11	;
UPDATE `items` SET `desc` = 'An upgraded arrow with improved accuracy and damage.'  WHERE `id` = 	12	;
UPDATE `items` SET `desc` = 'An arrow coated with a poisonous substance capable of inflicting additional damage over time.'  WHERE `id` = 	13	;
UPDATE `items` SET `desc` = 'A specialized arrow designed for hunting small game without damaging their pelts.'  WHERE `id` = 	14	;
UPDATE `items` SET `desc` = 'A projectile consisting of weights attached to ropes used to immobilize targets.'  WHERE `id` = 	15	;
UPDATE `items` SET `desc` = 'A reinforced bola ammunition with interwoven materials providing enhanced durability.'  WHERE `id` = 	16	;
UPDATE `items` SET `desc` = 'A bola ammunition featuring iron spikes inflicting additional damage to immobilized targets.'  WHERE `id` = 	17	;
UPDATE `items` SET `desc` = 'A weighted throwing weapon used to ensnare and immobilize targets.'  WHERE `id` = 	18	;
UPDATE `items` SET `desc` = 'An explosive device with a short fuse capable of causing significant damage.'  WHERE `id` = 	19	;
UPDATE `items` SET `desc` = 'Ammunition specifically designed for powerful elephant rifles providing superior stopping power.'  WHERE `id` = 	20	;
UPDATE `items` SET `desc` = 'Ammunition for a throwing knife used as a versatile and silent weapon.'  WHERE `id` = 	21	;
UPDATE `items` SET `desc` = 'A glass bottle filled with flammable liquid designed to burst into flames upon impact.'  WHERE `id` = 	22	;
UPDATE `items` SET `desc` = 'Ammunition for a pistol with explosive properties causing significant damage upon impact.'  WHERE `id` = 	23	;
UPDATE `items` SET `desc` = 'High-velocity ammunition specifically designed for pistols providing increased range and damage.'  WHERE `id` = 	24	;
UPDATE `items` SET `desc` = 'Standard ammunition used with pistols for self-defense and combat.'  WHERE `id` = 	25	;
UPDATE `items` SET `desc` = 'Ammunition with a split point tip designed to cause more damage and improve accuracy.'  WHERE `id` = 	26	;
UPDATE `items` SET `desc` = 'Ammunition designed to enhance the velocity and accuracy of pistol shots.'  WHERE `id` = 	27	;
UPDATE `items` SET `desc` = 'A glass bottle filled with a poisonous substance used to coat weapons and inflict additional damage.'  WHERE `id` = 	28	;
UPDATE `items` SET `desc` = 'Ammunition for a repeater rifle with explosive properties causing significant damage upon impact.'  WHERE `id` = 	29	;
UPDATE `items` SET `desc` = 'High-velocity ammunition specifically designed for repeater rifles providing increased range and damage.'  WHERE `id` = 	30	;
UPDATE `items` SET `desc` = 'Standard ammunition used with repeater rifles for self-defense and combat.'  WHERE `id` = 	31	;
UPDATE `items` SET `desc` = 'Ammunition with a split point tip designed to cause more damage and improve accuracy when used with repeater rifles.'  WHERE `id` = 	32	;
UPDATE `items` SET `desc` = 'Ammunition designed to enhance the velocity and accuracy of repeater rifle shots.'  WHERE `id` = 	33	;
UPDATE `items` SET `desc` = 'Ammunition for a revolver with explosive properties causing significant damage upon impact.'  WHERE `id` = 	34	;
UPDATE `items` SET `desc` = 'High-velocity ammunition specifically designed for revolvers providing increased range and damage.'  WHERE `id` = 	35	;
UPDATE `items` SET `desc` = 'Standard ammunition used with revolvers for self-defense and combat.'  WHERE `id` = 	36	;
UPDATE `items` SET `desc` = 'Ammunition with a split point tip designed to cause more damage and improve accuracy when used with revolvers.'  WHERE `id` = 	37	;
UPDATE `items` SET `desc` = 'Ammunition designed to enhance the velocity and accuracy of revolver shots.'  WHERE `id` = 	38	;
UPDATE `items` SET `desc` = 'Ammunition for a rifle with explosive properties causing significant damage upon impact.'  WHERE `id` = 	39	;
UPDATE `items` SET `desc` = 'High-velocity ammunition specifically designed for rifles providing increased range and damage.'  WHERE `id` = 	40	;
UPDATE `items` SET `desc` = 'Standard ammunition used with rifles for self-defense and combat.'  WHERE `id` = 	41	;
UPDATE `items` SET `desc` = 'Ammunition with a split point tip designed to cause more damage and improve accuracy when used with rifles.'  WHERE `id` = 	42	;
UPDATE `items` SET `desc` = 'Ammunition designed to enhance the velocity and accuracy of rifle shots.'  WHERE `id` = 	43	;
UPDATE `items` SET `desc` = 'Ammunition for a shotgun with explosive properties causing significant damage upon impact.'  WHERE `id` = 	44	;
UPDATE `items` SET `desc` = 'Ammunition designed to ignite targets causing them to burst into flames.'  WHERE `id` = 	45	;
UPDATE `items` SET `desc` = 'Standard ammunition used with shotguns for self-defense and combat.'  WHERE `id` = 	46	;
UPDATE `items` SET `desc` = 'Ammunition with a single solid projectile offering increased accuracy and range for shotguns.'  WHERE `id` = 	47	;
UPDATE `items` SET `desc` = 'Ammo used for Tomahawk throwing weapons'  WHERE `id` = 	48	;
UPDATE `items` SET `desc` = 'Ammo used for Varmint rifles'  WHERE `id` = 	49	;
UPDATE `items` SET `desc` = 'Ammo used for tranquilizing animals with Varmint rifles'  WHERE `id` = 	50	;
UPDATE `items` SET `desc` = 'Ammo used for crafting Volatile Dynamite'  WHERE `id` = 	51	;
UPDATE `items` SET `desc` = 'Ammo used for crafting Volatile Molotovs'  WHERE `id` = 	52	;
UPDATE `items` SET `desc` = 'A medicine used to counteract the effects of poison'  WHERE `id` = 	53	;
UPDATE `items` SET `desc` = 'A poison used to fend off snakes'  WHERE `id` = 	617	;
UPDATE `items` SET `desc` = 'A juicy and delicious fruit'  WHERE `id` = 	54	;
UPDATE `items` SET `desc` = 'A barrel filled with fresh apples'  WHERE `id` = 	762	;
UPDATE `items` SET `desc` = 'A basket filled with fresh apples'  WHERE `id` = 	763	;
UPDATE `items` SET `desc` = 'A mashed mixture of mint and berries used for crafting Moonshine'  WHERE `id` = 	55	;
UPDATE `items` SET `desc` = 'A strong alcoholic beverage made from mint and berries'  WHERE `id` = 	56	;
UPDATE `items` SET `desc` = 'A barrel filled with fresh apples'  WHERE `id` = 	634	;
UPDATE `items` SET `desc` = 'A basket filled with fresh apples'  WHERE `id` = 	635	;
UPDATE `items` SET `desc` = 'A seed used for growing apple trees'  WHERE `id` = 	727	;
UPDATE `items` SET `desc` = 'Sharp claws harvested from an Armadillo'  WHERE `id` = 	449	;
UPDATE `items` SET `desc` = 'A pelt taken from an Armadillo'  WHERE `id` = 	448	;
UPDATE `items` SET `desc` = 'A valuable pelt from a Copperhead Snake.'  WHERE `id` = 	487	;
UPDATE `items` SET `desc` = 'A medium-sized Bluegil fish.'  WHERE `id` = 	57	;
UPDATE `items` SET `desc` = 'A small Bluegil fish.'  WHERE `id` = 	58	;
UPDATE `items` SET `desc` = 'A medium-sized Bullhead fish.'  WHERE `id` = 	59	;
UPDATE `items` SET `desc` = 'A small Bullhead fish.'  WHERE `id` = 	60	;
UPDATE `items` SET `desc` = 'A medium-sized Pickerel fish.'  WHERE `id` = 	61	;
UPDATE `items` SET `desc` = 'A small Pickerel fish.'  WHERE `id` = 	62	;
UPDATE `items` SET `desc` = 'A large Largemouth Bass fish.'  WHERE `id` = 	63	;
UPDATE `items` SET `desc` = 'A medium-sized Perch fish.'  WHERE `id` = 	64	;
UPDATE `items` SET `desc` = 'A small Perch fish.'  WHERE `id` = 	65	;
UPDATE `items` SET `desc` = 'A Rainbow Trout fish.'  WHERE `id` = 	66	;
UPDATE `items` SET `desc` = 'A medium-sized Redfin Pickerel fish.'  WHERE `id` = 	67	;
UPDATE `items` SET `desc` = 'A small Redfin Pickerel fish.'  WHERE `id` = 	68	;
UPDATE `items` SET `desc` = 'A medium-sized Rockbass fish.'  WHERE `id` = 	69	;
UPDATE `items` SET `desc` = 'A small Rockbass fish.'  WHERE `id` = 	70	;
UPDATE `items` SET `desc` = 'A Sockeye Salmon fish.'  WHERE `id` = 	71	;
UPDATE `items` SET `desc` = 'A small and tasty bass fish.'  WHERE `id` = 	72	;
UPDATE `items` SET `desc` = 'Skin obtained from a badger.'  WHERE `id` = 	491	;
UPDATE `items` SET `desc` = 'Used as bait to attract fish while fishing.'  WHERE `id` = 	73	;
UPDATE `items` SET `desc` = 'A delicious and nutritious tropical fruit.'  WHERE `id` = 	74	;
UPDATE `items` SET `desc` = 'A medical item used to dress wounds.'  WHERE `id` = 	75	;
UPDATE `items` SET `desc` = 'A container made of wood or metal used for storing or transporting goods.'  WHERE `id` = 	800	;
UPDATE `items` SET `desc` = 'A flying mammal known for its nocturnal habits.'  WHERE `id` = 	420	;
UPDATE `items` SET `desc` = 'An edible mushroom with a brown cap and yellow pores.'  WHERE `id` = 	76	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow Bay Bolete mushrooms.'  WHERE `id` = 	77	;
UPDATE `items` SET `desc` = 'Skin obtained from a black bear.'  WHERE `id` = 	452	;
UPDATE `items` SET `desc` = 'Beak obtained from a cormorant bird.'  WHERE `id` = 	528	;
UPDATE `items` SET `desc` = 'Feather obtained from a cormorant bird.'  WHERE `id` = 	527	;
UPDATE `items` SET `desc` = 'A candle made from a glass bottle.'  WHERE `id` = 	663	;
UPDATE `items` SET `desc` = 'A bench made from the hide and bones of a bear.'  WHERE `id` = 	773	;
UPDATE `items` SET `desc` = 'Sharp claws obtained from a bear.'  WHERE `id` = 	450	;
UPDATE `items` SET `desc` = 'A tooth obtained from a bear.'  WHERE `id` = 	451	;
UPDATE `items` SET `desc` = 'A bench made from the hide and bones of a bear.'  WHERE `id` = 	645	;
UPDATE `items` SET `desc` = 'A flat and scaly tail obtained from a beaver.'  WHERE `id` = 	542	;
UPDATE `items` SET `desc` = 'A pelt obtained from a beaver.'  WHERE `id` = 	541	;
UPDATE `items` SET `desc` = 'Fresh and tender beef meat.'  WHERE `id` = 	567	;
UPDATE `items` SET `desc` = 'Dried and seasoned beef meat.'  WHERE `id` = 	78	;
UPDATE `items` SET `desc` = 'An alcoholic beverage brewed from grains.'  WHERE `id` = 	79	;
UPDATE `items` SET `desc` = 'A container holding multiple bottles of beer.'  WHERE `id` = 	586	;
UPDATE `items` SET `desc` = 'A large chest for storing items.'  WHERE `id` = 	658	;
UPDATE `items` SET `desc` = 'Meat obtained from a large game animal.'  WHERE `id` = 	565	;
UPDATE `items` SET `desc` = 'Large piece of leather.'  WHERE `id` = 	80	;
UPDATE `items` SET `desc` = 'Meat obtained from a bird.'  WHERE `id` = 	569	;
UPDATE `items` SET `desc` = 'A horn obtained from a bison.'  WHERE `id` = 	461	;
UPDATE `items` SET `desc` = 'A pelt obtained from a bison.'  WHERE `id` = 	462	;
UPDATE `items` SET `desc` = 'A type of bitter herb.'  WHERE `id` = 	81	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow bitter weed.'  WHERE `id` = 	82	;
UPDATE `items` SET `desc` = 'An ale made from blackberries.'  WHERE `id` = 	83	;
UPDATE `items` SET `desc` = 'A small and sweet black-colored berry.'  WHERE `id` = 	84	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow blackberries.'  WHERE `id` = 	85	;
UPDATE `items` SET `desc` = 'A small dark purple berry with a tart flavor.'  WHERE `id` = 	86	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow black currants.'  WHERE `id` = 	87	;
UPDATE `items` SET `desc` = 'A box used for storing blankets.'  WHERE `id` = 	760	;
UPDATE `items` SET `desc` = 'A box used for storing blankets.'  WHERE `id` = 	632	;
UPDATE `items` SET `desc` = 'A type of flower with red petals.'  WHERE `id` = 	88	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow blood flowers.'  WHERE `id` = 	89	;
UPDATE `items` SET `desc` = 'A small sweet fruit with a bluish color.'  WHERE `id` = 	90	;
UPDATE `items` SET `desc` = 'A colorful bird known as blue jay.'  WHERE `id` = 	421	;
UPDATE `items` SET `desc` = 'A dresser with a brown mirror.'  WHERE `id` = 	652	;
UPDATE `items` SET `desc` = 'A large tusk obtained from a boar.'  WHERE `id` = 	456	;
UPDATE `items` SET `desc` = 'A pelt obtained from a boar.'  WHERE `id` = 	457	;
UPDATE `items` SET `desc` = 'A snake skin obtained from a boa.'  WHERE `id` = 	486	;
UPDATE `items` SET `desc` = 'An egg cooked by boiling.'  WHERE `id` = 	91	;
UPDATE `items` SET `desc` = 'A beak obtained from a red-footed booby bird.'  WHERE `id` = 	501	;
UPDATE `items` SET `desc` = 'A feather obtained from a red-footed booby bird.'  WHERE `id` = 	500	;
UPDATE `items` SET `desc` = 'A written or printed work consisting of pages.'  WHERE `id` = 	92	;
UPDATE `items` SET `desc` = 'A license granting permission to be a bounty hunter.'  WHERE `id` = 	93	;
UPDATE `items` SET `desc` = 'A collection of flowers arranged in an artistic way.'  WHERE `id` = 	342	;
UPDATE `items` SET `desc` = 'A beak obtained from a parrot.'  WHERE `id` = 	522	;
UPDATE `items` SET `desc` = 'A feather obtained from a parrot.'  WHERE `id` = 	521	;
UPDATE `items` SET `desc` = 'Antlers obtained from a buck.'  WHERE `id` = 	459	;
UPDATE `items` SET `desc` = 'A pelt obtained from a buck.'  WHERE `id` = 	460	;
UPDATE `items` SET `desc` = 'A horn obtained from a bull.'  WHERE `id` = 	463	;
UPDATE `items` SET `desc` = 'A pelt obtained from a bull.'  WHERE `id` = 	464	;
UPDATE `items` SET `desc` = 'A type of tall wetland plant.'  WHERE `id` = 	94	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow bulrushes.'  WHERE `id` = 	95	;
UPDATE `items` SET `desc` = 'A bed with two tiers designed for multiple occupants.'  WHERE `id` = 	665	;
UPDATE `items` SET `desc` = 'The root of a burdock plant often used for medicinal purposes.'  WHERE `id` = 	96	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow burdock roots.'  WHERE `id` = 	97	;
UPDATE `items` SET `desc` = 'A small table used for butchering animals.'  WHERE `id` = 	583	;
UPDATE `items` SET `desc` = 'A medium-sized table used for butchering animals.'  WHERE `id` = 	582	;
UPDATE `items` SET `desc` = 'A large table used for butchering animals.'  WHERE `id` = 	581	;
UPDATE `items` SET `desc` = 'A dresser made of brown wood.'  WHERE `id` = 	651	;
UPDATE `items` SET `desc` = 'A device used to capture photographs.'  WHERE `id` = 	346	;
UPDATE `items` SET `desc` = 'A fire pit used for cooking and warmth during camping.'  WHERE `id` = 	98	;
UPDATE `items` SET `desc` = 'A wax candle that provides light.'  WHERE `id` = 	661	;
UPDATE `items` SET `desc` = 'A walking stick for support and stability.'  WHERE `id` = 	344	;
UPDATE `items` SET `desc` = 'A small colorful bird known for its distinctive crest.'  WHERE `id` = 	422	;
UPDATE `items` SET `desc` = 'A vibrant red flower often found near water.'  WHERE `id` = 	99	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow Cardinal Flowers.'  WHERE `id` = 	100	;
UPDATE `items` SET `desc` = 'An orange root vegetable commonly used in cooking.'  WHERE `id` = 	101	;
UPDATE `items` SET `desc` = 'A medium-sized bird with a distinctive crest and red tips on its wings.'  WHERE `id` = 	423	;
UPDATE `items` SET `desc` = 'A type of edible mushroom with a fruity aroma.'  WHERE `id` = 	102	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow Chanterelles mushrooms.'  WHERE `id` = 	103	;
UPDATE `items` SET `desc` = 'A type of fish commonly found in cold deep lakes and rivers.'  WHERE `id` = 	104	;
UPDATE `items` SET `desc` = 'A storage container used to store items securely.'  WHERE `id` = 	578	;
UPDATE `items` SET `desc` = 'A form of tobacco that is chewed rather than smoked.'  WHERE `id` = 	105	;
UPDATE `items` SET `desc` = 'A feather obtained from a chicken.'  WHERE `id` = 	525	;
UPDATE `items` SET `desc` = 'The internal organ of a chicken.'  WHERE `id` = 	526	;
UPDATE `items` SET `desc` = 'A small striped rodent known for its burrowing habits.'  WHERE `id` = 	419	;
UPDATE `items` SET `desc` = 'A beautiful Choc Daisy.'  WHERE `id` = 	106	;
UPDATE `items` SET `desc` = 'A seed to grow Choc Daisies.'  WHERE `id` = 	107	;
UPDATE `items` SET `desc` = 'A fine cigar for relaxing.'  WHERE `id` = 	108	;
UPDATE `items` SET `desc` = 'A cigarette for a quick smoke.'  WHERE `id` = 	109	;
UPDATE `items` SET `desc` = 'A filter for cigarettes.'  WHERE `id` = 	110	;
UPDATE `items` SET `desc` = 'A ticket for a movie or event.'  WHERE `id` = 	351	;
UPDATE `items` SET `desc` = 'A block of clay for crafting.'  WHERE `id` = 	111	;
UPDATE `items` SET `desc` = 'A cleanser for various uses.'  WHERE `id` = 	340	;
UPDATE `items` SET `desc` = 'A bench made of cloth material.'  WHERE `id` = 	776	;
UPDATE `items` SET `desc` = 'A line for hanging clothes.'  WHERE `id` = 	766	;
UPDATE `items` SET `desc` = 'A line for hanging clothes.'  WHERE `id` = 	638	;
UPDATE `items` SET `desc` = 'A bench made of cloth material.'  WHERE `id` = 	648	;
UPDATE `items` SET `desc` = 'A chunk of coal for fuel.'  WHERE `id` = 	112	;
UPDATE `items` SET `desc` = 'Claws from a rooster.'  WHERE `id` = 	499	;
UPDATE `items` SET `desc` = 'Feathers from a rooster.'  WHERE `id` = 	498	;
UPDATE `items` SET `desc` = 'Cocoa beans for making chocolate.'  WHERE `id` = 	113	;
UPDATE `items` SET `desc` = 'Seeds to grow cocoa plants.'  WHERE `id` = 	733	;
UPDATE `items` SET `desc` = 'Decorations for a coffin.'  WHERE `id` = 	629	;
UPDATE `items` SET `desc` = 'A device used to condense substances.'  WHERE `id` = 	816	;
UPDATE `items` SET `desc` = 'A beak from a condor bird.'  WHERE `id` = 	480	;
UPDATE `items` SET `desc` = 'A beautiful feather from a condor.'  WHERE `id` = 	479	;
UPDATE `items` SET `desc` = 'A dried Bluegil fish.'  WHERE `id` = 	114	;
UPDATE `items` SET `desc` = 'A hearty breakfast meal.'  WHERE `id` = 	115	;
UPDATE `items` SET `desc` = 'Sweet and sticky caramel.'  WHERE `id` = 	116	;
UPDATE `items` SET `desc` = 'A delicious chocolate bar.'  WHERE `id` = 	117	;
UPDATE `items` SET `desc` = 'A warm cup of coffee.'  WHERE `id` = 	118	;
UPDATE `items` SET `desc` = 'A refreshing fruit salad.'  WHERE `id` = 	119	;
UPDATE `items` SET `desc` = 'Dried and seasoned game meat.'  WHERE `id` = 	120	;
UPDATE `items` SET `desc` = 'A compact cube of hay.'  WHERE `id` = 	121	;
UPDATE `items` SET `desc` = 'A bundle of Chanterelle mushrooms.'  WHERE `id` = 	122	;
UPDATE `items` SET `desc` = 'Plump and juicy Evergreen Huckleberries.'  WHERE `id` = 	123	;
UPDATE `items` SET `desc` = 'Fragrant oregano leaves.'  WHERE `id` = 	124	;
UPDATE `items` SET `desc` = 'A delicate vanilla flower.'  WHERE `id` = 	125	;
UPDATE `items` SET `desc` = 'Tart and refreshing Wintergreen Berries.'  WHERE `id` = 	126	;
UPDATE `items` SET `desc` = 'Canned kidney beans.'  WHERE `id` = 	127	;
UPDATE `items` SET `desc` = 'A tool for breaking locks.'  WHERE `id` = 	128	;
UPDATE `items` SET `desc` = 'A hearty meat stew.'  WHERE `id` = 	129	;
UPDATE `items` SET `desc` = 'Medicinal treatment.'  WHERE `id` = 	130	;
UPDATE `items` SET `desc` = 'Juicy and ripe peach.'  WHERE `id` = 	131	;
UPDATE `items` SET `desc` = 'A sweet and juicy pear.'  WHERE `id` = 	132	;
UPDATE `items` SET `desc` = 'Refreshing water infused with berries.'  WHERE `id` = 	133	;
UPDATE `items` SET `desc` = 'A dried and preserved salmon.'  WHERE `id` = 	134	;
UPDATE `items` SET `desc` = 'Canned salmon.'  WHERE `id` = 	135	;
UPDATE `items` SET `desc` = 'A cooked and seasoned trout.'  WHERE `id` = 	136	;
UPDATE `items` SET `desc` = 'A mix of various edible vegetables.'  WHERE `id` = 	137	;
UPDATE `items` SET `desc` = 'A cooked Bluegil fish served with vegetables.'  WHERE `id` = 	138	;
UPDATE `items` SET `desc` = 'A piece of copper.'  WHERE `id` = 	139	;
UPDATE `items` SET `desc` = 'Fresh and juicy corn.'  WHERE `id` = 	140	;
UPDATE `items` SET `desc` = 'Seeds for growing corn.'  WHERE `id` = 	141	;
UPDATE `items` SET `desc` = 'A sharp tooth from a cougar.'  WHERE `id` = 	558	;
UPDATE `items` SET `desc` = 'The thick and durable skin of a cougar.'  WHERE `id` = 	557	;
UPDATE `items` SET `desc` = 'A taxidermy mount of a cougar.'  WHERE `id` = 	771	;
UPDATE `items` SET `desc` = 'A taxidermy mount of a cougar.'  WHERE `id` = 	643	;
UPDATE `items` SET `desc` = 'A long and curved horn from a cow.'  WHERE `id` = 	562	;
UPDATE `items` SET `desc` = 'The soft and furry pelt of a cow.'  WHERE `id` = 	561	;
UPDATE `items` SET `desc` = 'A sharp tooth from a coyote.'  WHERE `id` = 	560	;
UPDATE `items` SET `desc` = 'The fur pelt of a coyote.'  WHERE `id` = 	759	;
UPDATE `items` SET `desc` = 'The rugged and weathered skin of a coyote.'  WHERE `id` = 	559	;
UPDATE `items` SET `desc` = 'A taxidermy mount of a coyote.'  WHERE `id` = 	768	;
UPDATE `items` SET `desc` = 'The fur pelt of a coyote.'  WHERE `id` = 	631	;
UPDATE `items` SET `desc` = 'A taxidermy mount of a coyote.'  WHERE `id` = 	640	;
UPDATE `items` SET `desc` = 'A crab with a hard shell.'  WHERE `id` = 	425	;
UPDATE `items` SET `desc` = 'A fire used for crafting.'  WHERE `id` = 	753	;
UPDATE `items` SET `desc` = 'A fire used for crafting.'  WHERE `id` = 	625	;
UPDATE `items` SET `desc` = 'A small freshwater crustacean.'  WHERE `id` = 	424	;
UPDATE `items` SET `desc` = 'A fragrant herb with small purple flowers.'  WHERE `id` = 	142	;
UPDATE `items` SET `desc` = 'Seeds for growing creeping thyme.'  WHERE `id` = 	143	;
UPDATE `items` SET `desc` = 'A small and juicy creekplum.'  WHERE `id` = 	144	;
UPDATE `items` SET `desc` = 'Seeds for growing creekplums.'  WHERE `id` = 	145	;
UPDATE `items` SET `desc` = 'A pungent garlic with black bulbs.'  WHERE `id` = 	146	;
UPDATE `items` SET `desc` = 'Seeds for growing crows garlic.'  WHERE `id` = 	147	;
UPDATE `items` SET `desc` = 'A black-feathered bird with a sharp beak.'  WHERE `id` = 	426	;
UPDATE `items` SET `desc` = 'A long and slender beak from a crane.'  WHERE `id` = 	530	;
UPDATE `items` SET `desc` = 'A beautiful feather from a crane.'  WHERE `id` = 	529	;
UPDATE `items` SET `desc` = 'A double-sided candle with two wicks.'  WHERE `id` = 	660	;
UPDATE `items` SET `desc` = 'A decorative tent set with unique patterns.'  WHERE `id` = 	600	;
UPDATE `items` SET `desc` = 'A decorative tent set with unique patterns.'  WHERE `id` = 	601	;
UPDATE `items` SET `desc` = 'A decorative tent set with unique patterns.'  WHERE `id` = 	602	;
UPDATE `items` SET `desc` = 'The heart of a deer.'  WHERE `id` = 	466	;
UPDATE `items` SET `desc` = 'The soft and warm pelt of a deer.'  WHERE `id` = 	758	;
UPDATE `items` SET `desc` = 'The skin of a deer.'  WHERE `id` = 	465	;
UPDATE `items` SET `desc` = 'A taxidermy mount of a deer.'  WHERE `id` = 	770	;
UPDATE `items` SET `desc` = 'The soft and warm pelt of a deer.'  WHERE `id` = 	630	;
UPDATE `items` SET `desc` = 'A taxidermy mount of a deer.'  WHERE `id` = 	642	;
UPDATE `items` SET `desc` = 'A bundle of Desert Sage used for crafting and medicinal purposes.'  WHERE `id` = 	148	;
UPDATE `items` SET `desc` = 'A seed of Desert Sage that can be planted to grow Desert Sage plants.'  WHERE `id` = 	149	;
UPDATE `items` SET `desc` = 'A precious gemstone known for its brilliance and value.'  WHERE `id` = 	150	;
UPDATE `items` SET `desc` = 'The skin of a Desert Iguana commonly used for crafting and trading.'  WHERE `id` = 	551	;
UPDATE `items` SET `desc` = 'A traditional Native American ornament believed to filter out bad dreams and let only good dreams pass through.'  WHERE `id` = 	591	;
UPDATE `items` SET `desc` = 'A refreshing drink specially made for pets to keep them hydrated.'  WHERE `id` = 	151	;
UPDATE `items` SET `desc` = 'The rendered fat from a duck commonly used in cooking and baking.'  WHERE `id` = 	467	;
UPDATE `items` SET `desc` = 'An egg laid by a duck often used in various culinary preparations.'  WHERE `id` = 	152	;
UPDATE `items` SET `desc` = 'An explosive device consisting of a tube filled with explosive material used for various purposes including mining and demolition.'  WHERE `id` = 	153	;
UPDATE `items` SET `desc` = 'A feather obtained from an eagle often used for decorative purposes and in crafting.'  WHERE `id` = 	468	;
UPDATE `items` SET `desc` = 'The sharp claws of an eagle sometimes collected as a trophy or used in traditional medicine.'  WHERE `id` = 	469	;
UPDATE `items` SET `desc` = 'A small oval object laid by a female bird reptile or fish containing a fertilized embryo and nutrients for development.'  WHERE `id` = 	796	;
UPDATE `items` SET `desc` = 'Various types of eggs collected from different animals often used in cooking and crafting.'  WHERE `id` = 	154	;
UPDATE `items` SET `desc` = 'The beak of a Snowy Egret commonly used for crafting and trading.'  WHERE `id` = 	473	;
UPDATE `items` SET `desc` = 'A feather obtained from a Snowy Egret often used for decorative purposes and in crafting.'  WHERE `id` = 	472	;
UPDATE `items` SET `desc` = 'A large branched horn-like appendage grown by male elks.'  WHERE `id` = 	474	;
UPDATE `items` SET `desc` = 'A high-quality pelt obtained from an elk.'  WHERE `id` = 	475	;
UPDATE `items` SET `desc` = 'A precious green gemstone with a sparkling appearance.'  WHERE `id` = 	155	;
UPDATE `items` SET `desc` = 'A type of spice commonly used in cooking and herbal medicine.'  WHERE `id` = 	156	;
UPDATE `items` SET `desc` = 'Seeds that can be planted to grow English Mace plants.'  WHERE `id` = 	157	;
UPDATE `items` SET `desc` = 'A small dark purple berry known for its tart and sweet flavor.'  WHERE `id` = 	158	;
UPDATE `items` SET `desc` = 'Seeds that can be planted to grow Evergreen Huckleberry bushes.'  WHERE `id` = 	159	;
UPDATE `items` SET `desc` = 'A handheld device with flat blades used to create a breeze or provide cooling.'  WHERE `id` = 	160	;
UPDATE `items` SET `desc` = 'A stylish and well-crafted double-barreled firearm.'  WHERE `id` = 	667	;
UPDATE `items` SET `desc` = 'Rendered fat obtained from animals commonly used in cooking and crafting.'  WHERE `id` = 	161	;
UPDATE `items` SET `desc` = 'A lightweight and delicate feather often used for decorative purposes.'  WHERE `id` = 	162	;
UPDATE `items` SET `desc` = 'Nutritious food specifically formulated for dogs.'  WHERE `id` = 	163	;
UPDATE `items` SET `desc` = 'A substance used to enrich soil and promote plant growth.'  WHERE `id` = 	736	;
UPDATE `items` SET `desc` = 'Sacred fertilizer imbued with spiritual blessings known to enhance crop yield.'  WHERE `id` = 	738	;
UPDATE `items` SET `desc` = 'Fertilizer enriched with nutrients from various eggs providing excellent nourishment for plants.'  WHERE `id` = 	737	;
UPDATE `items` SET `desc` = 'Fertilizer containing organic matter from fresh produce enhancing soil fertility and plant health.'  WHERE `id` = 	740	;
UPDATE `items` SET `desc` = 'Fertilizer enriched with natural pulp or sap promoting robust growth and vitality in plants.'  WHERE `id` = 	741	;
UPDATE `items` SET `desc` = 'Fertilizer enriched with beneficial nutrients extracted from snakes promoting vigorous growth in plants.'  WHERE `id` = 	742	;
UPDATE `items` SET `desc` = 'Fertilizer infused with nutrients derived from squirrels providing essential elements for plant nourishment and vitality.'  WHERE `id` = 	743	;
UPDATE `items` SET `desc` = 'Fertilizer blended with fine particles of softwood enriching the soil with organic matter and enhancing plant development.'  WHERE `id` = 	745	;
UPDATE `items` SET `desc` = 'A potent and forbidden fertilizer concocted from mystical ingredients known to produce extraordinary growth in plants.'  WHERE `id` = 	739	;
UPDATE `items` SET `desc` = 'Fertilizer infused with the essence of Wojape a rare and powerful herb known for its profound effects on plant growth.'  WHERE `id` = 	744	;
UPDATE `items` SET `desc` = 'Fine threads or filaments extracted from plants or animals often used for crafting or weaving.'  WHERE `id` = 	164	;
UPDATE `items` SET `desc` = 'A aquatic creature with fins and scales commonly caught for food or sport.'  WHERE `id` = 	165	;
UPDATE `items` SET `desc` = 'A substance or lure used to attract fish increasing the chances of a successful catch.'  WHERE `id` = 	166	;
UPDATE `items` SET `desc` = 'A classic dish consisting of fried fish fillets and potato chips often served with tartar sauce.'  WHERE `id` = 	167	;
UPDATE `items` SET `desc` = 'Meat obtained from large fish species known for its tender texture and rich flavor.'  WHERE `id` = 	572	;
UPDATE `items` SET `desc` = 'A colorful and distinctive flag used to mark and identify a campsite or specific location.'  WHERE `id` = 	168	;
UPDATE `items` SET `desc` = 'Containers or receptacles designed to hold and display blooming flowers adding beauty and charm to any setting.'  WHERE `id` = 	628	;
UPDATE `items` SET `desc` = 'A sturdy barrel used for storing and preserving food items keeping them fresh and safe from pests.'  WHERE `id` = 	764	;
UPDATE `items` SET `desc` = 'A large barrel specifically designed for storing and transporting food ideal for provisioning during long journeys or expeditions.'  WHERE `id` = 	636	;
UPDATE `items` SET `desc` = 'The skin of a fox.'  WHERE `id` = 	512	;
UPDATE `items` SET `desc` = 'A tooth extracted from a fox.'  WHERE `id` = 	513	;
UPDATE `items` SET `desc` = 'Crispy and delicious fried potatoes.'  WHERE `id` = 	169	;
UPDATE `items` SET `desc` = 'A toxic variant of a frogbull.'  WHERE `id` = 	428	;
UPDATE `items` SET `desc` = 'A small creature found near water bodies.'  WHERE `id` = 	427	;
UPDATE `items` SET `desc` = 'The skin of a blacktail rattlesnake.'  WHERE `id` = 	488	;
UPDATE `items` SET `desc` = 'Fresh meat obtained from hunting animals.'  WHERE `id` = 	570	;
UPDATE `items` SET `desc` = 'A type of meat with a distinct gamey flavor.'  WHERE `id` = 	170	;
UPDATE `items` SET `desc` = 'The third stage of an alligator egg.'  WHERE `id` = 	171	;
UPDATE `items` SET `desc` = 'The fourth stage of an alligator egg.'  WHERE `id` = 	172	;
UPDATE `items` SET `desc` = 'The final stage of an alligator egg.'  WHERE `id` = 	173	;
UPDATE `items` SET `desc` = 'A part used in firearm manufacturing.'  WHERE `id` = 	761	;
UPDATE `items` SET `desc` = 'The skin of a grizzly bear.'  WHERE `id` = 	453	;
UPDATE `items` SET `desc` = 'A soothing tea made from ginseng roots.'  WHERE `id` = 	174	;
UPDATE `items` SET `desc` = 'A transparent bottle made of glass.'  WHERE `id` = 	175	;
UPDATE `items` SET `desc` = 'The skin of a green iguana.'  WHERE `id` = 	552	;
UPDATE `items` SET `desc` = 'The severed head of a goat.'  WHERE `id` = 	556	;
UPDATE `items` SET `desc` = 'The skin of a goat.'  WHERE `id` = 	555	;
UPDATE `items` SET `desc` = 'A bar made of solid gold.'  WHERE `id` = 	176	;
UPDATE `items` SET `desc` = 'A type of golden-colored currant.'  WHERE `id` = 	177	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow golden currants.'  WHERE `id` = 	178	;
UPDATE `items` SET `desc` = 'A shimmering gold-colored fish.'  WHERE `id` = 	179	;
UPDATE `items` SET `desc` = 'A shallow pan used for gold panning.'  WHERE `id` = 	181	;
UPDATE `items` SET `desc` = 'A ring made of solid gold.'  WHERE `id` = 	182	;
UPDATE `items` SET `desc` = 'A nugget of pure gold.'  WHERE `id` = 	180	;
UPDATE `items` SET `desc` = 'The beak of a goose.'  WHERE `id` = 	532	;
UPDATE `items` SET `desc` = 'A feather obtained from a goose.'  WHERE `id` = 	531	;
UPDATE `items` SET `desc` = 'An egg laid by a goose.'  WHERE `id` = 	183	;
UPDATE `items` SET `desc` = 'A traditional six-string guitar.'  WHERE `id` = 	341	;
UPDATE `items` SET `desc` = 'A cylindrical barrel used in firearm construction.'  WHERE `id` = 	633	;
UPDATE `items` SET `desc` = 'A set of items related to a gypsy wagon.'  WHERE `id` = 	585	;
UPDATE `items` SET `desc` = 'A grooming product for styling hair.'  WHERE `id` = 	184	;
UPDATE `items` SET `desc` = 'Metal restraints used for restraining someone.'  WHERE `id` = 	185	;
UPDATE `items` SET `desc` = 'A small axe with a short handle.'  WHERE `id` = 	186	;
UPDATE `items` SET `desc` = 'A feather obtained from a hawk.'  WHERE `id` = 	535	;
UPDATE `items` SET `desc` = 'The sharp claws of a hawk.'  WHERE `id` = 	536	;
UPDATE `items` SET `desc` = 'Bandages designed for treating injuries in pets.'  WHERE `id` = 	187	;
UPDATE `items` SET `desc` = 'A plant commonly used for its fiber.'  WHERE `id` = 	188	;
UPDATE `items` SET `desc` = 'A cigarette made from hemp leaves.'  WHERE `id` = 	189	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow hemp plants.'  WHERE `id` = 	615	;
UPDATE `items` SET `desc` = 'Medicine made from natural herbal ingredients.'  WHERE `id` = 	338	;
UPDATE `items` SET `desc` = 'A tonic made from herbal extracts.'  WHERE `id` = 	339	;
UPDATE `items` SET `desc` = 'A remedy made from various herbs.'  WHERE `id` = 	190	;
UPDATE `items` SET `desc` = 'A highly addictive and illegal drug.'  WHERE `id` = 	191	;
UPDATE `items` SET `desc` = 'Meat obtained from reptiles and amphibians.'  WHERE `id` = 	573	;
UPDATE `items` SET `desc` = 'A post used for tying up horses.'  WHERE `id` = 	580	;
UPDATE `items` SET `desc` = 'A gardening tool with a thin metal blade.'  WHERE `id` = 	679	;
UPDATE `items` SET `desc` = 'A sweet and sticky substance produced by bees.'  WHERE `id` = 	192	;
UPDATE `items` SET `desc` = 'A plant used in brewing beer.'  WHERE `id` = 	685	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow hop plants.'  WHERE `id` = 	684	;
UPDATE `items` SET `desc` = 'A brush used for grooming horses.'  WHERE `id` = 	193	;
UPDATE `items` SET `desc` = 'A set of items used for hitching horses.'  WHERE `id` = 	603	;
UPDATE `items` SET `desc` = 'Food provided to horses for sustenance.'  WHERE `id` = 	348	;
UPDATE `items` SET `desc` = 'A type of sage plant favored by hummingbirds.'  WHERE `id` = 	194	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow hummingbird sage.'  WHERE `id` = 	195	;
UPDATE `items` SET `desc` = 'Durable and strong wood used in various applications.'  WHERE `id` = 	196	;
UPDATE `items` SET `desc` = 'A type of tobacco used by Native Americans.'  WHERE `id` = 	197	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow Indian tobbaco plants.'  WHERE `id` = 	198	;
UPDATE `items` SET `desc` = 'A strong and durable metal.'  WHERE `id` = 	199	;
UPDATE `items` SET `desc` = 'A solid bar made of iron known for its strength and durability.'  WHERE `id` = 	200	;
UPDATE `items` SET `desc` = 'A concentrated form of iron extracted from natural sources.'  WHERE `id` = 	201	;
UPDATE `items` SET `desc` = 'A hammer with a head made of iron used for various construction and crafting purposes.'  WHERE `id` = 	202	;
UPDATE `items` SET `desc` = 'The beak of a Great Blue Heron known for its long and slender shape.'  WHERE `id` = 	534	;
UPDATE `items` SET `desc` = 'A feather obtained from a Great Blue Heron valued for its beauty and softness.'  WHERE `id` = 	533	;
UPDATE `items` SET `desc` = 'A sturdy counter surface typically found in kitchens providing space for food preparation and other tasks.'  WHERE `id` = 	611	;
UPDATE `items` SET `desc` = 'A versatile and stylish piece of cloth that can be worn around the neck or head for various purposes. It adds a touch of fashion to any outfit.'  WHERE `id` = 	203	;
UPDATE `items` SET `desc` = 'A set of Lamp Post 1'  WHERE `id` = 	606	;
UPDATE `items` SET `desc` = 'A set of Lamp Post 2'  WHERE `id` = 	607	;
UPDATE `items` SET `desc` = 'A lantern'  WHERE `id` = 	659	;
UPDATE `items` SET `desc` = 'Leather material'  WHERE `id` = 	204	;
UPDATE `items` SET `desc` = 'A leather chair'  WHERE `id` = 	748	;
UPDATE `items` SET `desc` = 'A leather chair'  WHERE `id` = 	620	;
UPDATE `items` SET `desc` = 'A legal book'  WHERE `id` = 	892	;
UPDATE `items` SET `desc` = 'A legendary pelt from an alligator'  WHERE `id` = 	417	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Teca Alligator'  WHERE `id` = 	400	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Sun Alligator'  WHERE `id` = 	401	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Banded Alligator'  WHERE `id` = 	402	;
UPDATE `items` SET `desc` = 'Legal paper'  WHERE `id` = 	891	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Deadly Bear'  WHERE `id` = 	376	;
UPDATE `items` SET `desc` = 'A legendary pelt from an Owiza Bear'  WHERE `id` = 	377	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Ridgeback Spirit Bear'  WHERE `id` = 	378	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Golden Spirit Bear'  WHERE `id` = 	379	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Grey Beaver'  WHERE `id` = 	397	;
UPDATE `items` SET `desc` = 'A legendary pelt from a White Beaver'  WHERE `id` = 	398	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Black Beaver'  WHERE `id` = 	399	;
UPDATE `items` SET `desc` = 'A legendary pelt from a Beaver'  WHERE `id` = 	411	;
UPDATE `items` SET `desc` = 'A pair of majestic horns from a legendary bison'  WHERE `id` = 	353	;
UPDATE `items` SET `desc` = 'A rare and valuable pelt from a legendary bison'  WHERE `id` = 	416	;
UPDATE `items` SET `desc` = 'An exquisite pelt from a legendary Tatanka Bison'  WHERE `id` = 	365	;
UPDATE `items` SET `desc` = 'A beautiful pelt from a legendary Winyan Bison'  WHERE `id` = 	366	;
UPDATE `items` SET `desc` = 'A prized pelt from a legendary Payata Bison'  WHERE `id` = 	367	;
UPDATE `items` SET `desc` = 'An exceptional pelt from a legendary Takanta Bison'  WHERE `id` = 	415	;
UPDATE `items` SET `desc` = 'A rare and sought-after pelt from a legendary boar'  WHERE `id` = 	414	;
UPDATE `items` SET `desc` = 'A magnificent pelt from a legendary Cogi Boar'  WHERE `id` = 	393	;
UPDATE `items` SET `desc` = 'A formidable pelt from a legendary Wakpa Boar'  WHERE `id` = 	394	;
UPDATE `items` SET `desc` = 'A rare pelt from a legendary Icahi Boar'  WHERE `id` = 	395	;
UPDATE `items` SET `desc` = 'An untamed pelt from a legendary Wildhog'  WHERE `id` = 	396	;
UPDATE `items` SET `desc` = 'A prized skin from a legendary buck'  WHERE `id` = 	410	;
UPDATE `items` SET `desc` = 'A splendid pelt from a legendary buck'  WHERE `id` = 	368	;
UPDATE `items` SET `desc` = 'A distinct pelt from a legendary Mudrunner Buck'  WHERE `id` = 	369	;
UPDATE `items` SET `desc` = 'A pristine pelt from a legendary Snow Buck'  WHERE `id` = 	370	;
UPDATE `items` SET `desc` = 'A mysterious pelt from a legendary Shadow Buck'  WHERE `id` = 	371	;
UPDATE `items` SET `desc` = 'A rare and valuable skin from a legendary cougar'  WHERE `id` = 	409	;
UPDATE `items` SET `desc` = 'A striking pelt from a legendary Iguga Cougar'  WHERE `id` = 	389	;
UPDATE `items` SET `desc` = 'An exceptional pelt from a legendary Maza Cougar'  WHERE `id` = 	390	;
UPDATE `items` SET `desc` = 'A majestic pelt from a legendary Sapa Cougar'  WHERE `id` = 	391	;
UPDATE `items` SET `desc` = 'A rare pelt from a legendary Black Cougar'  WHERE `id` = 	392	;
UPDATE `items` SET `desc` = 'A prized skin from a legendary coyote'  WHERE `id` = 	408	;
UPDATE `items` SET `desc` = 'A vibrant pelt from a legendary Red Streak Coyote'  WHERE `id` = 	386	;
UPDATE `items` SET `desc` = 'A dark and mysterious pelt from a legendary Midnight Paw Coyote'  WHERE `id` = 	387	;
UPDATE `items` SET `desc` = 'A rare pelt from a legendary Milk Coyote'  WHERE `id` = 	388	;
UPDATE `items` SET `desc` = 'A magnificent set of antlers from a legendary elk'  WHERE `id` = 	355	;
UPDATE `items` SET `desc` = 'An impressive pelt from a legendary elk'  WHERE `id` = 	403	;
UPDATE `items` SET `desc` = 'An exceptional pelt from a legendary Katata Elk'  WHERE `id` = 	362	;
UPDATE `items` SET `desc` = 'A rare pelt from a legendary Ozula Elk'  WHERE `id` = 	363	;
UPDATE `items` SET `desc` = 'An exquisite pelt from a legendary Inahme Elk'  WHERE `id` = 	364	;
UPDATE `items` SET `desc` = 'A pair of majestic antlers from a legendary buck'  WHERE `id` = 	356	;
UPDATE `items` SET `desc` = 'A rare and valuable pelt from a legendary boa'  WHERE `id` = 	418	;
UPDATE `items` SET `desc` = 'A beautiful pelt from a legendary Marble Fox'  WHERE `id` = 	360	;
UPDATE `items` SET `desc` = 'An exquisite pelt from a legendary Cross Fox'  WHERE `id` = 	361	;
UPDATE `items` SET `desc` = 'A valuable and versatile skin from a legendary fox'  WHERE `id` = 	413	;
UPDATE `items` SET `desc` = 'A formidable and sought-after skin from a legendary bear'  WHERE `id` = 	404	;
UPDATE `items` SET `desc` = 'A massive set of antlers from a legendary moose'  WHERE `id` = 	352	;
UPDATE `items` SET `desc` = 'A majestic pelt from a legendary moose'  WHERE `id` = 	405	;
UPDATE `items` SET `desc` = 'A pristine pelt from a legendary Snowflake Moose'  WHERE `id` = 	357	;
UPDATE `items` SET `desc` = 'An impressive pelt from a legendary Knight Moose'  WHERE `id` = 	358	;
UPDATE `items` SET `desc` = 'A distinctive pelt from a legendary Rudy Moose'  WHERE `id` = 	359	;
UPDATE `items` SET `desc` = 'A dark and elusive pelt from a legendary Nightwalker Panther'  WHERE `id` = 	383	;
UPDATE `items` SET `desc` = 'An ethereal pelt from a legendary Ghost Panther'  WHERE `id` = 	384	;
UPDATE `items` SET `desc` = 'A rare and valuable pelt from a legendary Iwakta Panther'  WHERE `id` = 	385	;
UPDATE `items` SET `desc` = 'A sleek and coveted skin from a legendary pronghorn'  WHERE `id` = 	407	;
UPDATE `items` SET `desc` = 'Impressive horns from a legendary ram'  WHERE `id` = 	354	;
UPDATE `items` SET `desc` = 'A distinctive pelt from a legendary ram'  WHERE `id` = 	412	;
UPDATE `items` SET `desc` = 'A rare and valuable pelt from a legendary Gabbro Horn Ram'  WHERE `id` = 	372	;
UPDATE `items` SET `desc` = 'An exceptional pelt from a legendary Chalk Horn Ram'  WHERE `id` = 	373	;
UPDATE `items` SET `desc` = 'An exquisite pelt from a legendary Rutile Horn Ram'  WHERE `id` = 	374	;
UPDATE `items` SET `desc` = 'An impressive pelt from a legendary GreatHorn Ram'  WHERE `id` = 	375	;
UPDATE `items` SET `desc` = 'A prized and valuable skin from a legendary wolf'  WHERE `id` = 	406	;
UPDATE `items` SET `desc` = 'A vibrant pelt from a legendary Emerald Wolf'  WHERE `id` = 	380	;
UPDATE `items` SET `desc` = 'nice item'  WHERE `id` = 	381	;
UPDATE `items` SET `desc` = 'A magnificent pelt from a legendary Moonstone Wolf'  WHERE `id` = 	382	;
UPDATE `items` SET `desc` = 'A preserved foot of a lizard'  WHERE `id` = 	554	;
UPDATE `items` SET `desc` = 'A unique and scaly skin from a lizard'  WHERE `id` = 	553	;
UPDATE `items` SET `desc` = 'A handy tool used for picking locks'  WHERE `id` = 	205	;
UPDATE `items` SET `desc` = 'A mold used for crafting lockpicks'  WHERE `id` = 	206	;
UPDATE `items` SET `desc` = 'A sturdy and rustic log bench design'  WHERE `id` = 	775	;
UPDATE `items` SET `desc` = 'A simple and natural log bench'  WHERE `id` = 	774	;
UPDATE `items` SET `desc` = 'A comfortable log bench for outdoor seating'  WHERE `id` = 	646	;
UPDATE `items` SET `desc` = 'A spacious log bench for outdoor gatherings'  WHERE `id` = 	647	;
UPDATE `items` SET `desc` = 'The beak of a common loon bird'  WHERE `id` = 	538	;
UPDATE `items` SET `desc` = 'A beautiful feather from a common loon bird'  WHERE `id` = 	537	;
UPDATE `items` SET `desc` = 'A comfortable and stylish lounge chair'  WHERE `id` = 	598	;
UPDATE `items` SET `desc` = 'A modern and luxurious lounge chair'  WHERE `id` = 	599	;
UPDATE `items` SET `desc` = 'A sturdy axe designed for cutting lumber'  WHERE `id` = 	345	;
UPDATE `items` SET `desc` = 'A small and silvery fish called mackerel'  WHERE `id` = 	207	;
UPDATE `items` SET `desc` = 'A book containing the guidelines and rituals for marriage'  WHERE `id` = 	894	;
UPDATE `items` SET `desc` = 'A legal document certifying a marriage'  WHERE `id` = 	895	;
UPDATE `items` SET `desc` = 'A mixture of ingredients used in the production of Alaskan gin'  WHERE `id` = 	824	;
UPDATE `items` SET `desc` = 'A blend of ingredients used in the production of Alaskan gin'  WHERE `id` = 	825	;
UPDATE `items` SET `desc` = 'A mashed mixture of apples used for various recipes'  WHERE `id` = 	826	;
UPDATE `items` SET `desc` = 'A mashed mixture of blackberries used in cooking and beverages'  WHERE `id` = 	827	;
UPDATE `items` SET `desc` = 'A concentrated blackberry mash used for crafting high-quality beverages'  WHERE `id` = 	828	;
UPDATE `items` SET `desc` = 'A mashed mixture of peaches used in culinary preparations'  WHERE `id` = 	829	;
UPDATE `items` SET `desc` = 'A mashed mixture of plums used in cooking and distilling'  WHERE `id` = 	830	;
UPDATE `items` SET `desc` = 'A mashed mixture of raspberries used for culinary purposes'  WHERE `id` = 	831	;
UPDATE `items` SET `desc` = 'A concentrated raspberry mash used for crafting potent beverages'  WHERE `id` = 	832	;
UPDATE `items` SET `desc` = 'A powerful and highly concentrated mash batch for advanced recipes'  WHERE `id` = 	833	;
UPDATE `items` SET `desc` = 'Fresh and uncooked meat from various animals'  WHERE `id` = 	208	;
UPDATE `items` SET `desc` = 'A nutritious and creamy dairy product'  WHERE `id` = 	209	;
UPDATE `items` SET `desc` = 'A plant with milky sap used for medicinal purposes'  WHERE `id` = 	210	;
UPDATE `items` SET `desc` = 'Seeds of the milkweed plant for cultivation'  WHERE `id` = 	211	;
UPDATE `items` SET `desc` = 'An illegally distilled and potent alcoholic beverage'  WHERE `id` = 	212	;
UPDATE `items` SET `desc` = 'Impressive antlers shed by a moose'  WHERE `id` = 	548	;
UPDATE `items` SET `desc` = 'A large and thick fur coat from a moose'  WHERE `id` = 	549	;
UPDATE `items` SET `desc` = 'A medical prescription for morphine medication'  WHERE `id` = 	213	;
UPDATE `items` SET `desc` = 'A potent analgesic and narcotic medication'  WHERE `id` = 	214	;
UPDATE `items` SET `desc` = 'A set of equipment and supplies for a mountain camp'  WHERE `id` = 	608	;
UPDATE `items` SET `desc` = 'A large still used for distilling alcoholic beverages'  WHERE `id` = 	215	;
UPDATE `items` SET `desc` = 'The fur skin of a muskrat commonly used for crafting'  WHERE `id` = 	547	;
UPDATE `items` SET `desc` = 'Meat from mature sheep used in cooking'  WHERE `id` = 	216	;
UPDATE `items` SET `desc` = 'Small metal fasteners used for joining materials'  WHERE `id` = 	217	;
UPDATE `items` SET `desc` = 'A traditional native basket for carrying items'  WHERE `id` = 	593	;
UPDATE `items` SET `desc` = 'A second variation of a traditional native basket'  WHERE `id` = 	594	;
UPDATE `items` SET `desc` = 'A set of decorative native items for display'  WHERE `id` = 	584	;
UPDATE `items` SET `desc` = 'A traditional native pot for cooking and storage'  WHERE `id` = 	592	;
UPDATE `items` SET `desc` = 'A decorative native skull for ornamental purposes'  WHERE `id` = 	595	;
UPDATE `items` SET `desc` = 'A wagon set equipped for naturalists and explorers'  WHERE `id` = 	605	;
UPDATE `items` SET `desc` = 'A printed publication containing news and articles'  WHERE `id` = 	218	;
UPDATE `items` SET `desc` = 'A small bedside table for holding personal items'  WHERE `id` = 	653	;
UPDATE `items` SET `desc` = 'A chemical compound used in various industrial processes'  WHERE `id` = 	219	;
UPDATE `items` SET `desc` = 'A highly explosive liquid compound used in explosives'  WHERE `id` = 	220	;
UPDATE `items` SET `desc` = 'A standard table for dining or work purposes'  WHERE `id` = 	750	;
UPDATE `items` SET `desc` = 'A small book with blank pages for writing or drawing'  WHERE `id` = 	221	;
UPDATE `items` SET `desc` = 'An old bed that has seen better days.'  WHERE `id` = 	664	;
UPDATE `items` SET `desc` = 'A herb known for its medicinal properties.'  WHERE `id` = 	222	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow Oleander Sage.'  WHERE `id` = 	223	;
UPDATE `items` SET `desc` = 'Sharp claws from an opossum.'  WHERE `id` = 	515	;
UPDATE `items` SET `desc` = 'The fur and skin of an opossum.'  WHERE `id` = 	514	;
UPDATE `items` SET `desc` = 'A prestigious order awarded by the President.'  WHERE `id` = 	224	;
UPDATE `items` SET `desc` = 'A fragrant herb commonly used in cooking.'  WHERE `id` = 	225	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow Oregano.'  WHERE `id` = 	226	;
UPDATE `items` SET `desc` = 'Brightly colored feathers from a Hooded Oriole.'  WHERE `id` = 	430	;
UPDATE `items` SET `desc` = 'Vibrant feathers from an Oriole bird.'  WHERE `id` = 	429	;
UPDATE `items` SET `desc` = 'Feathers shed by an owl.'  WHERE `id` = 	539	;
UPDATE `items` SET `desc` = 'Sharp claws from an owl.'  WHERE `id` = 	540	;
UPDATE `items` SET `desc` = 'A sturdy horn from an Angus Bull.'  WHERE `id` = 	545	;
UPDATE `items` SET `desc` = 'The thick fur and skin of an Angus Bull.'  WHERE `id` = 	546	;
UPDATE `items` SET `desc` = 'Intense and captivating eyes from a panther.'  WHERE `id` = 	564	;
UPDATE `items` SET `desc` = 'The sleek and supple skin of a panther.'  WHERE `id` = 	563	;
UPDATE `items` SET `desc` = 'Sheets of paper for writing or drawing.'  WHERE `id` = 	227	;
UPDATE `items` SET `desc` = 'A stylish and functional parasol to shield from the sun.'  WHERE `id` = 	343	;
UPDATE `items` SET `desc` = 'A mushroom with a wide umbrella-like cap.'  WHERE `id` = 	228	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow parasol mushrooms.'  WHERE `id` = 	229	;
UPDATE `items` SET `desc` = 'Seeds that can be planted to grow peach trees.'  WHERE `id` = 	735	;
UPDATE `items` SET `desc` = 'The beak of a peasant bird.'  WHERE `id` = 	518	;
UPDATE `items` SET `desc` = 'A feather from a peasant bird.'  WHERE `id` = 	517	;
UPDATE `items` SET `desc` = 'The fur of a peccary a pig-like mammal.'  WHERE `id` = 	550	;
UPDATE `items` SET `desc` = 'The beak of a pelican bird.'  WHERE `id` = 	520	;
UPDATE `items` SET `desc` = 'A feather from a pelican bird.'  WHERE `id` = 	519	;
UPDATE `items` SET `desc` = 'A writing instrument used to apply ink.'  WHERE `id` = 	896	;
UPDATE `items` SET `desc` = 'A preserved mount of a pheasant bird for display.'  WHERE `id` = 	641	;
UPDATE `items` SET `desc` = 'A preserved mount of a pheasant bird for display.'  WHERE `id` = 	769	;
UPDATE `items` SET `desc` = 'A tool with a pointed end and a handle used for breaking up rocks and mining.'  WHERE `id` = 	230	;
UPDATE `items` SET `desc` = 'A pigeon bird.'  WHERE `id` = 	431	;
UPDATE `items` SET `desc` = 'The skin and fur of a pig.'  WHERE `id` = 	516	;
UPDATE `items` SET `desc` = 'A tubular device used for smoking tobacco or other substances.'  WHERE `id` = 	231	;
UPDATE `items` SET `desc` = 'A pipe made of copper.'  WHERE `id` = 	835	;
UPDATE `items` SET `desc` = 'A small timepiece designed to be carried in a pocket.'  WHERE `id` = 	232	;
UPDATE `items` SET `desc` = 'A complete set for playing poker including a table and cards.'  WHERE `id` = 	579	;
UPDATE `items` SET `desc` = 'The meat from a pig commonly used for cooking and eating.'  WHERE `id` = 	571	;
UPDATE `items` SET `desc` = 'The fat obtained from a pig often used in cooking and making lard.'  WHERE `id` = 	458	;
UPDATE `items` SET `desc` = 'A large pot used in the distillation process for making alcohol.'  WHERE `id` = 	836	;
UPDATE `items` SET `desc` = 'A pot typically used for cooking and boiling ingredients.'  WHERE `id` = 	626	;
UPDATE `items` SET `desc` = 'An edible starchy tuber that is commonly used in cooking.'  WHERE `id` = 	233	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow potato plants.'  WHERE `id` = 	731	;
UPDATE `items` SET `desc` = 'The beak of a prairie chicken a bird species found in grassland habitats.'  WHERE `id` = 	509	;
UPDATE `items` SET `desc` = 'A type of poppy flower that is native to prairie regions.'  WHERE `id` = 	234	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow prairie poppy flowers.'  WHERE `id` = 	235	;
UPDATE `items` SET `desc` = 'A feather from a prairie chicken bird often used in crafts and decorations.'  WHERE `id` = 	508	;
UPDATE `items` SET `desc` = 'The horn of a pronghorn a mammal native to North America.'  WHERE `id` = 	511	;
UPDATE `items` SET `desc` = 'The skin of a pronghorn known for its soft and durable fur.'  WHERE `id` = 	510	;
UPDATE `items` SET `desc` = 'A set of keys used to unlock jail cells and gates.'  WHERE `id` = 	236	;
UPDATE `items` SET `desc` = 'A soft and moist mass of plant fibers typically obtained from crushing or processing plant materials.'  WHERE `id` = 	237	;
UPDATE `items` SET `desc` = 'A piece of bread used as bait for fishing.'  WHERE `id` = 	838	;
UPDATE `items` SET `desc` = 'A container typically made of wood used for storing and aging moonshine.'  WHERE `id` = 	238	;
UPDATE `items` SET `desc` = 'The beak of a quail bird often used for crafts and decorative purposes.'  WHERE `id` = 	471	;
UPDATE `items` SET `desc` = 'A feather from a quail bird known for its small size and distinctive patterns.'  WHERE `id` = 	470	;
UPDATE `items` SET `desc` = 'A hard mineral often used in jewelry and decorative items.'  WHERE `id` = 	239	;
UPDATE `items` SET `desc` = 'The foot of a rabbit sometimes considered a good luck charm.'  WHERE `id` = 	507	;
UPDATE `items` SET `desc` = 'The skin of a rabbit commonly used in making fur garments and accessories.'  WHERE `id` = 	506	;
UPDATE `items` SET `desc` = 'The skin of a raccoon known for its distinctive ringed tail and soft fur.'  WHERE `id` = 	504	;
UPDATE `items` SET `desc` = 'A tooth from a raccoon often used in crafts and jewelry.'  WHERE `id` = 	505	;
UPDATE `items` SET `desc` = 'An explosive oil used for various purposes such as creating dynamite and explosives.'  WHERE `id` = 	240	;
UPDATE `items` SET `desc` = 'The horn of a ram a male sheep often used in crafting and decoration.'  WHERE `id` = 	454	;
UPDATE `items` SET `desc` = 'The fur and skin of a ram known for its warmth and durability.'  WHERE `id` = 	455	;
UPDATE `items` SET `desc` = 'The preserved head of a ram often used as a hunting trophy or decorative item.'  WHERE `id` = 	241	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow plants resembling a rams head.'  WHERE `id` = 	242	;
UPDATE `items` SET `desc` = 'A type of ale infused with the flavor of raspberries.'  WHERE `id` = 	243	;
UPDATE `items` SET `desc` = 'A small rodent known for its agility and ability to adapt to various environments.'  WHERE `id` = 	432	;
UPDATE `items` SET `desc` = 'The claws of a raven bird often used for crafts and jewelry.'  WHERE `id` = 	502	;
UPDATE `items` SET `desc` = 'A feather from a raven bird known for its glossy black color and sleek appearance.'  WHERE `id` = 	503	;
UPDATE `items` SET `desc` = 'A rectangular-shaped table suitable for various purposes such as dining or work.'  WHERE `id` = 	751	;
UPDATE `items` SET `desc` = 'A table with a rectangular shape often used for dining or as a work surface.'  WHERE `id` = 	623	;
UPDATE `items` SET `desc` = 'A type of raspberry with a red color commonly used in desserts and preserves.'  WHERE `id` = 	244	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow red raspberry plants.'  WHERE `id` = 	245	;
UPDATE `items` SET `desc` = 'A type of sage plant with red-colored flowers often used in herbal remedies and smudging ceremonies.'  WHERE `id` = 	246	;
UPDATE `items` SET `desc` = 'A seed that can be planted to grow red sage plants.'  WHERE `id` = 	247	;
UPDATE `items` SET `desc` = 'A replacement barrel for a repeater firearm used for improving accuracy and performance.'  WHERE `id` = 	248	;
UPDATE `items` SET `desc` = 'A mold used for casting the components of a repeater firearm.'  WHERE `id` = 	249	;
UPDATE `items` SET `desc` = 'A replacement receiver for a repeater firearm which houses the firing mechanism.'  WHERE `id` = 	250	;
UPDATE `items` SET `desc` = 'A mold used for casting the receiver of a repeater firearm.'  WHERE `id` = 	251	;
UPDATE `items` SET `desc` = 'A replacement stock for a repeater firearm providing stability and control.'  WHERE `id` = 	252	;
UPDATE `items` SET `desc` = 'A replacement barrel for a revolver firearm used for improving accuracy and performance.'  WHERE `id` = 	253	;
UPDATE `items` SET `desc` = 'A replacement cylinder for a revolver firearm which holds the ammunition.'  WHERE `id` = 	254	;
UPDATE `items` SET `desc` = 'A replacement handle for a revolver firearm providing grip and control.'  WHERE `id` = 	255	;
UPDATE `items` SET `desc` = 'A mold used for casting the components of a revolver firearm.'  WHERE `id` = 	256	;
UPDATE `items` SET `desc` = 'A replacement barrel for a rifle firearm used for improving accuracy and performance.'  WHERE `id` = 	257	;
UPDATE `items` SET `desc` = 'A mold used for casting the components of a rifle firearm.'  WHERE `id` = 	258	;
UPDATE `items` SET `desc` = 'A replacement receiver for a rifle firearm which houses the firing mechanism.'  WHERE `id` = 	259	;
UPDATE `items` SET `desc` = 'A mold used for casting the receiver of a rifle firearm.'  WHERE `id` = 	260	;
UPDATE `items` SET `desc` = 'A replacement stock for a rifle firearm providing stability and control.'  WHERE `id` = 	261	;
UPDATE `items` SET `desc` = 'A small insect commonly found in households and other environments.'  WHERE `id` = 	262	;
UPDATE `items` SET `desc` = 'A set of tools and materials used for planning a robbery or heist.'  WHERE `id` = 	604	;
UPDATE `items` SET `desc` = 'A small songbird known for its red breast and melodious voice.'  WHERE `id` = 	433	;
UPDATE `items` SET `desc` = 'A solid mineral material that forms the Earths crust commonly found in various shapes and sizes.'  WHERE `id` = 	263	;
UPDATE `items` SET `desc` = 'A thin lightweight paper used for rolling cigarettes or other smoking materials.'  WHERE `id` = 	264	;
UPDATE `items` SET `desc` = 'A circular table with a flat top surface often used for dining or discussions.'  WHERE `id` = 	749	;
UPDATE `items` SET `desc` = 'A table with a round top surface typically used for dining or meetings.'  WHERE `id` = 	621	;
UPDATE `items` SET `desc` = 'The long slender beak of a Roseta Spoonbill bird known for its distinctive shape and color.'  WHERE `id` = 	497	;
UPDATE `items` SET `desc` = 'A feather from a Roseta Spoonbill bird often used in crafts and decorative items.'  WHERE `id` = 	496	;
UPDATE `items` SET `desc` = 'A flexible elastic material derived from the sap of certain plants or synthesized chemically.'  WHERE `id` = 	265	;
UPDATE `items` SET `desc` = 'A cylindrical tube made of rubber commonly used for various applications such as plumbing or medical procedures.'  WHERE `id` = 	841	;
UPDATE `items` SET `desc` = 'Fresh pork salamelle'  WHERE `id` = 	266	;
UPDATE `items` SET `desc` = 'Fresh salmon'  WHERE `id` = 	267	;
UPDATE `items` SET `desc` = 'Common salt'  WHERE `id` = 	268	;
UPDATE `items` SET `desc` = 'Saltbush plant'  WHERE `id` = 	269	;
UPDATE `items` SET `desc` = 'Seed of Saltbush plant'  WHERE `id` = 	270	;
UPDATE `items` SET `desc` = 'Sticky sap'  WHERE `id` = 	271	;
UPDATE `items` SET `desc` = 'Medicinal sarsaparilla'  WHERE `id` = 	272	;
UPDATE `items` SET `desc` = 'Measuring scale'  WHERE `id` = 	273	;
UPDATE `items` SET `desc` = 'Scented glad'  WHERE `id` = 	492	;
UPDATE `items` SET `desc` = 'Beak of a seagull'  WHERE `id` = 	495	;
UPDATE `items` SET `desc` = 'Feather from a seagull'  WHERE `id` = 	494	;
UPDATE `items` SET `desc` = 'Opportunity for a second chance'  WHERE `id` = 	274	;
UPDATE `items` SET `desc` = 'Head of a sheep'  WHERE `id` = 	493	;
UPDATE `items` SET `desc` = 'Empty shell casing'  WHERE `id` = 	275	;
UPDATE `items` SET `desc` = 'Target for shooting practice'  WHERE `id` = 	613	;
UPDATE `items` SET `desc` = 'Barrel for a shotgun'  WHERE `id` = 	276	;
UPDATE `items` SET `desc` = 'Mold for a shotgun'  WHERE `id` = 	277	;
UPDATE `items` SET `desc` = 'Stock for a shotgun'  WHERE `id` = 	278	;
UPDATE `items` SET `desc` = 'Delicious shrimp stew'  WHERE `id` = 	279	;
UPDATE `items` SET `desc` = 'Functional side table'  WHERE `id` = 	782	;
UPDATE `items` SET `desc` = 'Stylish side table'  WHERE `id` = 	783	;
UPDATE `items` SET `desc` = 'A beautiful side table'  WHERE `id` = 	784	;
UPDATE `items` SET `desc` = 'A stylish side table'  WHERE `id` = 	654	;
UPDATE `items` SET `desc` = 'An elegant side table'  WHERE `id` = 	655	;
UPDATE `items` SET `desc` = 'A modern side table'  WHERE `id` = 	656	;
UPDATE `items` SET `desc` = 'A comfortable single bed'  WHERE `id` = 	666	;
UPDATE `items` SET `desc` = 'A decorative skull post'  WHERE `id` = 	597	;
UPDATE `items` SET `desc` = 'A small storage chest'  WHERE `id` = 	657	;
UPDATE `items` SET `desc` = 'A small melted candle'  WHERE `id` = 	662	;
UPDATE `items` SET `desc` = 'A small piece of leather'  WHERE `id` = 	280	;
UPDATE `items` SET `desc` = 'A snake skin'  WHERE `id` = 	281	;
UPDATE `items` SET `desc` = 'A tooth from a snake'  WHERE `id` = 	490	;
UPDATE `items` SET `desc` = 'Poison extracted from a snake'  WHERE `id` = 	282	;
UPDATE `items` SET `desc` = 'A bottle of Soborno alcohol'  WHERE `id` = 	283	;
UPDATE `items` SET `desc` = 'A beautiful scarlet songbird'  WHERE `id` = 	435	;
UPDATE `items` SET `desc` = 'A lovely songbird'  WHERE `id` = 	434	;
UPDATE `items` SET `desc` = 'A common sparrow'  WHERE `id` = 	436	;
UPDATE `items` SET `desc` = 'A sparrow'  WHERE `id` = 	437	;
UPDATE `items` SET `desc` = 'A golden sparrow'  WHERE `id` = 	438	;
UPDATE `items` SET `desc` = 'A black squirrel'  WHERE `id` = 	441	;
UPDATE `items` SET `desc` = 'A gray squirrel'  WHERE `id` = 	439	;
UPDATE `items` SET `desc` = 'A Red squirrel'  WHERE `id` = 	440	;
UPDATE `items` SET `desc` = 'A standard table for various uses.'  WHERE `id` = 	622	;
UPDATE `items` SET `desc` = 'A standing torch to provide light.'  WHERE `id` = 	612	;
UPDATE `items` SET `desc` = 'A delicious steak for a hearty meal.'  WHERE `id` = 	284	;
UPDATE `items` SET `desc` = 'A balanced meal with steak and vegetables.'  WHERE `id` = 	285	;
UPDATE `items` SET `desc` = 'A kit for setting up a still to make distilled spirits.'  WHERE `id` = 	843	;
UPDATE `items` SET `desc` = 'A stimulant to boost a horses performance.'  WHERE `id` = 	286	;
UPDATE `items` SET `desc` = 'Various stolen items of questionable origin.'  WHERE `id` = 	287	;
UPDATE `items` SET `desc` = 'A durable hammer made of stone.'  WHERE `id` = 	288	;
UPDATE `items` SET `desc` = 'Tough and chewy meat that requires thorough cooking.'  WHERE `id` = 	574	;
UPDATE `items` SET `desc` = 'A sweet and granulated substance used for sweetening.'  WHERE `id` = 	289	;
UPDATE `items` SET `desc` = 'Seeds for growing sugarcane.'  WHERE `id` = 	290	;
UPDATE `items` SET `desc` = 'A compact form of sugar for easy use.'  WHERE `id` = 	347	;
UPDATE `items` SET `desc` = 'A yellow chemical element often used in manufacturing.'  WHERE `id` = 	291	;
UPDATE `items` SET `desc` = 'A synthetic substance used for various purposes.'  WHERE `id` = 	292	;
UPDATE `items` SET `desc` = 'A package containing synthetic substances.'  WHERE `id` = 	293	;
UPDATE `items` SET `desc` = 'A medical instrument used for injecting fluids.'  WHERE `id` = 	294	;
UPDATE `items` SET `desc` = 'A certification for the proper use of syringes.'  WHERE `id` = 	295	;
UPDATE `items` SET `desc` = 'A portable shelter for camping or temporary use.'  WHERE `id` = 	296	;
UPDATE `items` SET `desc` = 'A tent specifically designed for trading purposes.'  WHERE `id` = 	588	;
UPDATE `items` SET `desc` = 'A basic tent for camping.'  WHERE `id` = 	589	;
UPDATE `items` SET `desc` = 'A canvas shade for shelter.'  WHERE `id` = 	590	;
UPDATE `items` SET `desc` = 'A bottle of tequila.'  WHERE `id` = 	297	;
UPDATE `items` SET `desc` = 'A traditional Texas bonnet.'  WHERE `id` = 	298	;
UPDATE `items` SET `desc` = 'Seeds to grow Texas Bonnet flowers.'  WHERE `id` = 	299	;
UPDATE `items` SET `desc` = 'A sturdy table made of timber.'  WHERE `id` = 	752	;
UPDATE `items` SET `desc` = 'A table made of timber.'  WHERE `id` = 	624	;
UPDATE `items` SET `desc` = 'A traditional Native American tipi.'  WHERE `id` = 	596	;
UPDATE `items` SET `desc` = 'A toad found in the desert.'  WHERE `id` = 	444	;
UPDATE `items` SET `desc` = 'A toad that carries poison.'  WHERE `id` = 	443	;
UPDATE `items` SET `desc` = 'A common toad.'  WHERE `id` = 	442	;
UPDATE `items` SET `desc` = 'A license for setting up a camp.'  WHERE `id` = 	300	;
UPDATE `items` SET `desc` = 'A barrel for storing tools.'  WHERE `id` = 	767	;
UPDATE `items` SET `desc` = 'A barrel used for storing tools.'  WHERE `id` = 	639	;
UPDATE `items` SET `desc` = 'A key to unlock a train.'  WHERE `id` = 	301	;
UPDATE `items` SET `desc` = 'A table used for serving food.'  WHERE `id` = 	614	;
UPDATE `items` SET `desc` = 'A mash made from ginseng.'  WHERE `id` = 	302	;
UPDATE `items` SET `desc` = 'Moonshine infused with ginseng.'  WHERE `id` = 	303	;
UPDATE `items` SET `desc` = 'A fish of the trout family.'  WHERE `id` = 	304	;
UPDATE `items` SET `desc` = 'The beak of a turkey.'  WHERE `id` = 	484	;
UPDATE `items` SET `desc` = 'A feather from a turkey.'  WHERE `id` = 	483	;
UPDATE `items` SET `desc` = 'The shell of a turtle.'  WHERE `id` = 	305	;
UPDATE `items` SET `desc` = 'A tooth extracted from a turtle.'  WHERE `id` = 	482	;
UPDATE `items` SET `desc` = 'A medication called Tylenol.'  WHERE `id` = 	306	;
UPDATE `items` SET `desc` = 'A wooden coffin.'  WHERE `id` = 	609	;
UPDATE `items` SET `desc` = 'A coffin decorated with flowers.'  WHERE `id` = 	610	;
UPDATE `items` SET `desc` = 'Sugar used for horses owned by Brad.'  WHERE `id` = 	350	;
UPDATE `items` SET `desc` = 'Feed for horses.'  WHERE `id` = 	349	;
UPDATE `items` SET `desc` = 'A flower known as Vanille.'  WHERE `id` = 	307	;
UPDATE `items` SET `desc` = 'Lean meat obtained from deer.'  WHERE `id` = 	566	;
UPDATE `items` SET `desc` = 'A delicate flower called Violet Snowdrop.'  WHERE `id` = 	308	;
UPDATE `items` SET `desc` = 'Seeds to grow Violet Snowdrop flowers.'  WHERE `id` = 	309	;
UPDATE `items` SET `desc` = 'A strong alcoholic beverage known as Vodka.'  WHERE `id` = 	310	;
UPDATE `items` SET `desc` = 'An egg laid by a Volture bird.'  WHERE `id` = 	311	;
UPDATE `items` SET `desc` = 'A taxidermy of a vulture bird.'  WHERE `id` = 	772	;
UPDATE `items` SET `desc` = 'A preserved vulture bird for display.'  WHERE `id` = 	644	;
UPDATE `items` SET `desc` = 'A tub used for washing clothes or other items.'  WHERE `id` = 	637	;
UPDATE `items` SET `desc` = 'Clean drinking water.'  WHERE `id` = 	312	;
UPDATE `items` SET `desc` = 'A large barrel used for storing water.'  WHERE `id` = 	587	;
UPDATE `items` SET `desc` = 'A jug-shaped container used for watering plants.'  WHERE `id` = 	313	;
UPDATE `items` SET `desc` = 'A watering jug filled with dirty water.'  WHERE `id` = 	314	;
UPDATE `items` SET `desc` = 'An empty watering jug.'  WHERE `id` = 	315	;
UPDATE `items` SET `desc` = 'A device used for pumping water.'  WHERE `id` = 	755	;
UPDATE `items` SET `desc` = 'A pump designed to move water.'  WHERE `id` = 	627	;
UPDATE `items` SET `desc` = 'An alcoholic beverage known as whisky.'  WHERE `id` = 	316	;
UPDATE `items` SET `desc` = 'A bench made from wicker material.'  WHERE `id` = 	778	;
UPDATE `items` SET `desc` = 'A bench constructed with wicker material.'  WHERE `id` = 	650	;
UPDATE `items` SET `desc` = 'Mashed blackberries used for making cider.'  WHERE `id` = 	317	;
UPDATE `items` SET `desc` = 'Homemade moonshine crafted from blackberries.'  WHERE `id` = 	318	;
UPDATE `items` SET `desc` = 'A type of carrot that grows in the wild.'  WHERE `id` = 	319	;
UPDATE `items` SET `desc` = 'Seeds to cultivate wild carrots.'  WHERE `id` = 	320	;
UPDATE `items` SET `desc` = 'A wild plant known as Feverfew.'  WHERE `id` = 	321	;
UPDATE `items` SET `desc` = 'Seeds to grow Feverfew plants.'  WHERE `id` = 	322	;
UPDATE `items` SET `desc` = 'A type of mint that grows in the wild.'  WHERE `id` = 	323	;
UPDATE `items` SET `desc` = 'Seeds to cultivate wild mint.'  WHERE `id` = 	324	;
UPDATE `items` SET `desc` = 'A rhubarb plant that grows in the wild.'  WHERE `id` = 	325	;
UPDATE `items` SET `desc` = 'Seeds to grow wild rhubarb.'  WHERE `id` = 	326	;
UPDATE `items` SET `desc` = 'An alcoholic beverage made from fermented grapes.'  WHERE `id` = 	327	;
UPDATE `items` SET `desc` = 'Berries from the wintergreen plant.'  WHERE `id` = 	328	;
UPDATE `items` SET `desc` = 'Seeds to cultivate wintergreen berries.'  WHERE `id` = 	329	;
UPDATE `items` SET `desc` = 'A flowering plant called Wisteria.'  WHERE `id` = 	330	;
UPDATE `items` SET `desc` = 'Seeds to grow Wisteria plants.'  WHERE `id` = 	331	;
UPDATE `items` SET `desc` = 'A traditional Native American sauce made from berries.'  WHERE `id` = 	332	;
UPDATE `items` SET `desc` = 'The heart of a wolf.'  WHERE `id` = 	476	;
UPDATE `items` SET `desc` = 'The skin of a wolf.'  WHERE `id` = 	477	;
UPDATE `items` SET `desc` = 'A tooth extracted from a wolf.'  WHERE `id` = 	478	;
UPDATE `items` SET `desc` = 'A type of wood that is soft and easy to work with.'  WHERE `id` = 	333	;
UPDATE `items` SET `desc` = 'A bench made from wood material.'  WHERE `id` = 	777	;
UPDATE `items` SET `desc` = 'A chair made from wood material.'  WHERE `id` = 	747	;
UPDATE `items` SET `desc` = 'A bench constructed with wooden material.'  WHERE `id` = 	649	;
UPDATE `items` SET `desc` = 'Boards made from wood material.'  WHERE `id` = 	334	;
UPDATE `items` SET `desc` = 'The skin and feathers of a woodpecker.'  WHERE `id` = 	445	;
UPDATE `items` SET `desc` = 'The skin and feathers of a woodpecker.'  WHERE `id` = 	446	;
UPDATE `items` SET `desc` = 'A chair made from wood material.'  WHERE `id` = 	619	;
UPDATE `items` SET `desc` = 'Fiber obtained from the fleece of sheep.'  WHERE `id` = 	335	;
UPDATE `items` SET `desc` = 'The skin of a western rattlesnake.'  WHERE `id` = 	489	;
UPDATE `items` SET `desc` = 'The skin of a watersnake.'  WHERE `id` = 	485	;
UPDATE `items` SET `desc` = 'A flowering plant known as Yarrow.'  WHERE `id` = 	336	;
UPDATE `items` SET `desc` = 'Seeds to grow Yarrow plants.'  WHERE `id` = 	337	;
