INSERT IGNORE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `id`, `metadata`, `desc`) VALUES
('absinthe','Absinthe',10,1,'item_standard',1,1600,'{}','An anise-flavoured spirit derived from several plants, including the flowers and leaves of Artemisia absinthium'),
('bacon','Bacon',10,1,'item_standard',1,1601,'{}','Bacon what else do you need to know?'),
('beartrap','Beartrap',10,1,'item_standard',1,1602,'{}','A sturdy beartrap used for catching animals or stopping trespassers'),
('biscuitbox','Biscuitbox',10,1,'item_standard',1,1603,'{}','A box of assorted biscuits.'),
('bolts','Bolts',10,1,'item_standard',1,1604,'{}','Metal bolts often used in construction.'),
('brokenpearlnecklace','Broken Pearl Necklace',10,1,'item_standard',1,1605,'{}','A broken pearl necklace.'),
('cheesecake','Cheesecake',10,1,'item_standard',1,1606,'{}','A tasty cheesecake.'),
('chococake','Chocolate Cake',10,1,'item_standard',1,1607,'{}','A tasty chocolate cake.'),
('cloth','Cloth',10,1,'item_standard',1,1608,'{}','Simple cloth with many uses.'),
('coffeebeans','Coffee Beans',10,1,'item_standard',1,1609,'{}','Coffee beans for making that beautiful brew.'),
('coffeefilter','Coffee Filter',10,1,'item_standard',1,1610,'{}','A simple coffee filter.'),
('collector_fossil_bivalve','Bivalve Fossil',10,1,'item_standard',1,1611,'{}','A common fossilized mollusc, badly worn.'),
('collector_fossil_brachiopod','Brachiopod Fossil',10,1,'item_standard',1,1612,'{}','A common Brachiopod fossil with some chips and scrapes.'),
('collector_fossil_brow_horn','Brow Horn Fossil',10,1,'item_standard',1,1613,'{}','A rare fossilized brow horn, believed to have belonged to a Triceratops.'),
('collector_fossil_cephalopod','Cephalopod Fossil',10,1,'item_standard',1,1614,'{}','A common cephalopod fossil. Slightly damaged and brittle.'),
('collector_fossil_coral','Agatized Coral Fossil',10,1,'item_standard',1,1615,'{}','A common piece of agatized coral, weather-beaten but still striking.'),
('collector_fossil_neo','Neospirifer Fossil',10,1,'item_standard',1,1616,'{}','A common Neospirifer fossil, millions of years old. Good condition.'),
('collector_fossil_pet_wood','Common Petrified Wood Fossil',10,1,'item_standard',1,1617,'{}','A common chunk of wood turned to stone over the years.'),
('collector_fossil_pet_wood_rainbow','Rainbow Petrified Wood Fossil',10,1,'item_standard',1,1618,'{}','An uncommon piece of petrified wood filled with multicolored crystals.'),
('collector_fossil_pet_wood_yellow_cat','Yellow Cat Petrified Wood Fossil',10,1,'item_standard',1,1619,'{}','An uncommon lump of petrified wood featuring bright red and yellow colors.'),
('collector_fossil_sea_lily','Sea Lily Fossil',10,1,'item_standard',1,1620,'{}','An uncommon fossilized crinoid, a marine animal millions of years old.'),
('collector_fossil_sea_scorpion','Sea Scorpion Fossil',10,1,'item_standard',1,1621,'{}','An uncommon eurypterid fossil in good condition.'),
('collector_fossil_stone','Petoskey Stone Fossil',10,1,'item_standard',1,1622,'{}','A common rock made of fossilized coral. Unpolished.'),
('collector_fossil_tail_spike','Tail Spike Fossil',10,1,'item_standard',1,1623,'{}','A rare fossilized tail spike, thought to have belonged to a Stegosaurus.'),
('collector_fossil_toe_claw','Toe Sickle Claw Fossil',10,1,'item_standard',1,1624,'{}','A rare fossilized claw. Still sharp, it belonged to a genus of Dromaeosauridae.'),
('collector_fossil_tooth_mega','Upper Tooth Fossil',10,1,'item_standard',1,1625,'{}','A rare fossilized tooth from a Megalodon.'),
('collector_fossil_tooth_serrated','Serrated Tooth Fossil',10,1,'item_standard',1,1626,'{}','A rare and jagged fossilized tooth, once belonging to an Allosaurus.'),
('collector_fossil_tooth_trex','Front Tooth Fossil',10,1,'item_standard',1,1627,'{}','A rare fossilized front tooth, perhaps belonging to the recently discovered Manospondylus Gigas. Highly prized.'),
('collector_fossil_trilobite_crypto','Cryptolithus Trilobite Fossil',10,1,'item_standard',1,1628,'{}','A small, uncommon trilobite fossil. Good condition.'),
('collector_fossil_trilobite_iso','Isotelus Trilobite Fossil',10,1,'item_standard',1,1629,'{}','An uncommon fossil of a huge trilobite. Fully intact.'),
('collector_fossil_tully_monster','Tully Monster Fossil',10,1,'item_standard',1,1630,'{}','An uncommon Tullimonstrum fossil, nicely preserved.'),
('consumable_blueberrypie','Blueberry Pie',10,1,'item_standard',1,1631,'{}','A delicious pie made with blueberries.'),
('consumable_chickenpie','Chicken Pie',10,1,'item_standard',1,1632,'{}','A delicious pie made with chicken.'),
('consumable_chocolatecake','Chocolate Cake',10,1,'item_standard',1,1633,'{}','A tasty chocolate cake.'),
('consumable_chocolatecoffee','Chocolate Coffee',10,1,'item_standard',1,1634,'{}','A chocolate flaverd coffee drink.'),
('consumable_coffeecake','Coffee Cake',10,1,'item_standard',1,1635,'{}','A delicious coffee cake.'),
('consumable_crumbcake','Crumb Cake',10,1,'item_standard',1,1636,'{}','A delicious crumb cake.'),
('consumable_cupcake','Cupcake',10,1,'item_standard',1,1637,'{}','A delicious cupcake.'),
('consumable_donut','Donut',10,1,'item_standard',1,1638,'{}','A tasty donut.'),
('consumable_grapejelly','Grape Jelly',10,1,'item_standard',1,1639,'{}','Grape flavored jelly.'),
('consumable_horsepeppermints','Peppermint Stick',10,1,'item_standard',1,1640,'{}','Peppermint flavored candy stick.'),
('consumable_lemoncake','Lemon Cake',10,1,'item_standard',1,1641,'{}','A delicious lemon cake'),
('consumable_lemondrops','Leamon Drops',10,1,'item_standard',1,1642,'{}','Lemon flavored candy.'),
('consumable_peachcobbler','Peach Cobbler',10,1,'item_standard',1,1643,'{}','A tasty peach cobbler.'),
('consumable_peachjelly','Peach Jelly',10,1,'item_standard',1,1644,'{}','Peach flavored jelly.'),
('consumable_peppermint','Peppermint',10,1,'item_standard',1,1645,'{}','Peppermint flavored candy.'),
('consumable_poundcake','Pound Cake',10,1,'item_standard',1,1646,'{}','A delicious pound cake.'),
('consumable_pretzel','Pretzel',10,1,'item_standard',1,1647,'{}','A tasty pretzel with salt.'),
('consumable_raspberryjelly','Raspberry Jelly',10,1,'item_standard',1,1648,'{}','Raspberry flavored jelly.'),
('consumable_spongecake','Sponge Cake',10,1,'item_standard',1,1649,'{}','A soft and delicious spong cake.'),
('consumable_steakpie','Steak Pie',10,1,'item_standard',1,1650,'{}','A delicious pie made with beef.'),
('cordbow','Bow Cord',10,1,'item_standard',1,1651,'{}','Cord used for making a bow.'),
('crabbutter','Crab Butter',10,1,'item_standard',1,1652,'{}','Butter made from crab. Delicious on toast.'),
('crablegs','Crab Legs',10,1,'item_standard',1,1653,'{}','Legs from a crab.'),
('flour','Flour',10,1,'item_standard',1,1654,'{}','Ground up wheat used for cooking and baking.'),
('floursack','Flour Sack',10,1,'item_standard',1,1655,'{}','A sack of flour.'),
('glasseye','Glass Eye',10,1,'item_standard',1,1656,'{}','A glass eye. Probably lost in a bar fight.'),
('gold_panning_license','Gold Panning License',10,1,'item_standard',1,1657,'{}','A license to pan gold.'),
('grainmill','Grain Mill',10,1,'item_standard',1,1658,'{}','A hand-held Grain Mill for grinding grain.'),
('grapes','Grapes',10,1,'item_standard',1,1659,'{}','A tasty fruit that grows in clusters. Often used to make wine.'),
('grinder','Grinder',10,1,'item_standard',1,1660,'{}','Used to crush up and grind herbs and plants.'),
('handmixer','Handmixer',10,1,'item_standard',1,1661,'{}','A hand-held mixing device'),
('handsaw','Handsaw',10,1,'item_standard',1,1662,'{}','A hand saw used to cut wood'),
('iguanabits','Iguana Bits',10,1,'item_standard',1,1663,'{}','Tasy cooked Iguna pieces.'),
('ink','Ink',10,1,'item_standard',1,1664,'{}','A small bottle of ink.'),
('metal_gear','Metal gear',10,1,'item_standard',1,1665,'{}','A metal gear used in many machines.'),
('mexitillas','Mexitillas',10,1,'item_standard',1,1666,'{}','A can of mixed mexcian beans.'),
('mexitillastaco','Taco',10,1,'item_standard',1,1667,'{}','A delicous taco.'),
('money_coin','Coin',10,1,'item_standard',1,1668,'{}','A simple metal coin'),
('money_coinpurse','Coin Purse',10,1,'item_standard',1,1669,'{}','A small coin purse.'),
('pearl','Pearl',10,1,'item_standard',1,1670,'{}','A hard, glistening object produced within the soft tissue of a living shelled mollusk.'),
('planttrimmer2','Plant Trimmer',10,1,'item_standard',1,16710,'{}','A set plant trimmers to keep the weeds in check.'),
('provision_arrowhead_agate','Agate Arrowhead',10,1,'item_standard',1,16720,'{}','A rare arrowhead fashioned from sharp, colorful agate.'),
('provision_arrowhead_bone','Bone Arrowhead',10,1,'item_standard',1,1673,'{}','A serrated arrowhead made from animal bone.'),
('provision_arrowhead_chipped','Chipped Arrowhead',10,1,'item_standard',1,1674,'{}','A hurriedly made arrowhead made from chiseled flint.'),
('provision_arrowhead_crude','Crude Arrowhead',10,1,'item_standard',1,1675,'{}','A clumsily made flint arrowhead, blunt from age.'),
('provision_arrowhead_feldspar','Feldspar Arrowhead',10,1,'item_standard',1,1676,'{}','A mysterious arrowhead made from some sort of feldspar.'),
('provision_arrowhead_granite','Flint Arrowhead',10,1,'item_standard',1,1677,'{}','A strong arrowhead made of flint.'),
('provision_arrowhead_obsidian','Obsidian Arrowhead',10,1,'item_standard',1,1678,'{}','A valuable arrowhead of smooth, gleaming obsidian.'),
('provision_arrowhead_quartz','Quartz Arrowhead',10,1,'item_standard',1,1679,'{}','An eye-catching arrowhead of cut quartz, in good condition.'),
('provision_arrowhead_raw','Raw Arrowhead',10,1,'item_standard',1,1680,'{}','A roughly hacked arrowhead made from pale stone.'),
('provision_arrowhead_rough','Rough Arrowhead',10,1,'item_standard',1,1681,'{}','A stone arrowhead, badly weathered over time.'),
('provision_arrowhead_slate','Slate Arrowhead',10,1,'item_standard',1,1682,'{}','A carefully made, well-preserved slate arrowhead.'),
('provision_arrowhead_splintered','Splintered Arrowhead',10,1,'item_standard',1,1683,'{}','A partially damaged, jagged arrowhead made of chert.'),
('provision_asteroid_chunk','Meteorite',10,1,'item_standard',1,1684,'{}','A rock that has fallen from space.'),
('provision_bracelet_gold','Gold Bracelet',10,1,'item_standard',1,1685,'{}','A gold bracelet.'),
('provision_bracelet_platinum','Platinum Bracelet',10,1,'item_standard',1,1686,'{}','A platinum bracelet'),
('provision_bracelet_silver','Silver Bracelet',10,1,'item_standard',1,1687,'{}','A silver bracelet.'),
('provision_bra_shield','Brass Shield',10,1,'item_standard',1,1688,'{}','An old brass shield. Probably valuable.'),
('provision_buckle_gold','Gold Buckle',10,1,'item_standard',1,1689,'{}','A gold belt buckle.'),
('provision_buckle_platinum','Platinum Buckle',10,1,'item_standard',1,1690,'{}','A platinum belt buckle.'),
('provision_buckle_silver','Silver Buckle',10,1,'item_standard',1,1691,'{}','A silver belt buckle.'),
('provision_calderon_cross','Wooden Cross',10,1,'item_standard',1,1692,'{}','A simple wooden cross. Often used by preists and clergymen.'),
('provision_capitale','Capitale',10,1,'item_standard',1,1693,'{}','Capitale. very valuable.'),
('provision_coin_1700_ny_tkn','1700 New Yorke Token',10,1,'item_standard',1,1694,'{}','A rare 1700 New Yorke Token'),
('provision_coin_1787_cent_tkn','1787 One cent Token',10,1,'item_standard',1,1695,'{}','A rare 1787 One cent Token'),
('provision_coin_1789_pny','1789 Penny',10,1,'item_standard',1,1696,'{}','A rare 1789 Penny'),
('provision_coin_1792_lib_qtr','1792 Liberty Quarter',10,1,'item_standard',1,1697,'{}','A rare 1792 Liberty Quarter'),
('provision_coin_1792_nickel','1792 Nickel',10,1,'item_standard',1,1698,'{}','A rare 1792 Nickel'),
('provision_coin_1792_qtr','1792 Quarter',10,1,'item_standard',1,1699,'{}','A rare 1792 Quarter'),
('provision_coin_1794_slv_dlr','1794 Silver Dollar',10,1,'item_standard',1,1700,'{}','A rare 1794 Silver Dollar'),
('provision_coin_1795_hlf_eag','1795 Half Eagle',10,1,'item_standard',1,1701,'{}','A rare 1795 Half Eagle'),
('provision_coin_1796_hlf_pny','1796 Half Penny',10,1,'item_standard',1,1702,'{}','A rare 1796 Half Penny'),
('provision_coin_1797_gld_eag','1797 Gold Eagle',10,1,'item_standard',1,1703,'{}','A rare 1797 Gold Eagle'),
('provision_coin_1798_slv_dlr','1798 Silver Dollar',10,1,'item_standard',1,1704,'{}','A rare 1798 Silver Dollar'),
('provision_coin_1800_five_dlr','1800 Five Dollar',10,1,'item_standard',1,1705,'{}','A rare 1800 Five Dollar'),
('provision_coin_1800_gld_dlr','1800 Gold Dollar',10,1,'item_standard',1,1706,'{}','A rare 1800 Gold Dollar'),
('provision_coin_1800_gld_qtr','1800 Gold Quarter',10,1,'item_standard',1,1707,'{}','A rare 1800 Gold Quarter'),
('provision_coin_1800_hlf_dime','1800 Half Dime',10,1,'item_standard',1,1708,'{}','A rare 1800 Half Dime'),
('provision_db_finger_bone','Bone',10,1,'item_standard',1,1709,'{}','A small bone possibly from a finger.'),
('provision_diamond_ring','Diamond Ring',10,1,'item_standard',1,1710,'{}','A beautiful diamond ring.'),
('provision_disco_ammolite','Ammolite',10,1,'item_standard',1,1711,'{}','Fossilized shell of an ammonite.'),
('provision_disco_ancient_eagle','Ancient Eagle',10,1,'item_standard',1,1712,'{}','An ancient eagle statue.'),
('provision_disco_ancient_necklace','Ancient Necklace',10,1,'item_standard',1,1713,'{}','An ancient necklace.'),
('provision_disco_fertility_statue','Fertility Statue',10,1,'item_standard',1,1714,'{}','A statue that apparently possesses the power to grant fertility.'),
('provision_disco_fluorite','Fluorite',10,1,'item_standard',1,1715,'{}','The mineral form of calcium fluoride.'),
('provision_disco_shrunken_head','Shrunken Head',10,1,'item_standard',1,1716,'{}','A shurken head. possibly used in vodoo.'),
('provision_disco_urn','Urn',10,1,'item_standard',1,1717,'{}','A simple urn often used to hold things.'),
('provision_disco_viking_comb','Viking Comb',10,1,'item_standard',1,1718,'{}','A old viking comb.'),
('provision_dog_tag','Dog Tag',10,1,'item_standard',1,1719,'{}','A dog tag. Possibly from a soldier.'),
('provision_earring_gold','Gold Earring',10,1,'item_standard',1,1720,'{}','A gold earring.'),
('provision_earring_pearl','Pearl Earring',10,1,'item_standard',1,1721,'{}','A gold earring.'),
('provision_earring_platinum','Platinum Earring',10,1,'item_standard',1,1722,'{}','A beautiful pearl earring.'),
('provision_earring_silver','Silver Earring',10,1,'item_standard',1,1723,'{}','A silver earring.'),
('provision_generic_key','Key',10,1,'item_standard',1,1724,'{}','A simple key.'),
('provision_hrlm_brush_boar','Boar bristle Brush',10,1,'item_standard',1,1725,'{}','A beautifully made boar bristle brush.'),
('provision_hrlm_brush_ebony','Ebony Hairbrush',10,1,'item_standard',1,1726,'{}','A delicate and finely crafted ebony brush.'),
('provision_hrlm_brush_goathair','Goat Hair Brush',10,1,'item_standard',1,1727,'{}','A exquisite hand crafted goat hair brush.'),
('provision_hrlm_brush_horsehair','Horse Hair brush',10,1,'item_standard',1,1728,'{}','A finley made horse hair brush.'),
('provision_hrlm_brush_rosewood','Rosewood Hairbrush',10,1,'item_standard',1,1729,'{}','A hand carved rosewood brush.'),
('provision_hrlm_brush_rosewood_ng','New Guinea Rosewood Hairbrush',10,1,'item_standard',1,1730,'{}','An exotic new guinea rosewood hairbrush.'),
('provision_hrlm_comb_boxwood','Boxwood Comb',10,1,'item_standard',1,1731,'{}','A finley made boxwood comb.'),
('provision_hrlm_comb_cherrywood','Cherrywood Comb',10,1,'item_standard',1,1732,'{}','A exquisite cheerywood comb.'),
('provision_hrlm_comb_ivory','Ivory Comb',10,1,'item_standard',1,1733,'{}','A delicate ivory comb.'),
('provision_hrlm_comb_tortoiseshell','Tortoiseshell Comb',10,1,'item_standard',1,1734,'{}','A beautiful tortoiseshell comb.'),
('provision_hrlm_hairpin_ebony','Ebony Hairpin',10,1,'item_standard',1,1735,'{}','A exquisite ebony hairpin.'),
('provision_hrlm_hairpin_ivory','Ivory Hairpin',10,1,'item_standard',1,1736,'{}','A delicate ivory hairpin.'),
('provision_hrlm_hairpin_jade','Jade Hairpin',10,1,'item_standard',1,1737,'{}','A exotic jade hairpin.'),
('provision_hrlm_hairpin_metal','Meatl Hairpin',10,1,'item_standard',1,1738,'{}','A beautiful metal hairpin.'),
('provision_hrlm_hairpin_wooden','Wooden Hairpin',10,1,'item_standard',1,1739,'{}','A hand carved wooden hairpin.'),
('provision_jewelry_amethyst_necklace','Richelieu Amethyst Necklace',10,1,'item_standard',1,1740,'{}','A delicate necklace featuring a duo of purple amethyst and silver pearl.'),
('provision_jewelry_blck_pearl_necklace','Tuamotu Pearl Necklace',10,1,'item_standard',1,1741,'{}','A silk strung necklace of magnificent black Tahitian pearls.'),
('provision_jewelry_box','Jewelry Box',10,1,'item_standard',1,1742,'{}','A small jewlery box.'),
('provision_jewelry_carved_bracelet','Elliston Carved Bracelet',10,1,'item_standard',1,1743,'{}','A solid gold bracelet with elegant etching.'),
('provision_jewelry_coral_dngl_earring','Emmeline Coral Earrings',10,1,'item_standard',1,1744,'{}','Drop hook earrings of polished pink coral set in gold.'),
('provision_jewelry_coral_ring','Harland Coral Ring',10,1,'item_standard',1,1745,'{}','A delicate gold ring featuring a large angel skin coral.'),
('provision_jewelry_dmnd_bngle_bracelet','Abelló Ruby Bangle Bracelet',10,1,'item_standard',1,1746,'{}','A hinged gold bangle with a series of claw set rubies.'),
('provision_jewelry_dmnd_pendt_earring','Orchidée Diamond Earrings',10,1,'item_standard',1,1747,'{}','Earrings set with clusters of brilliant cut diamonds in a floral pattern.'),
('provision_jewelry_elk_tooth_earring','Sterling Tooth Earrings',10,1,'item_standard',1,1748,'{}','A striking pair of elk teeth set into silver.'),
('provision_jewelry_emerald_earring','Duchess Emerald Earrings',10,1,'item_standard',1,1749,'{}','A famous set of oval cut emeralds fashioned into earrings.'),
('provision_jewelry_emerald_ring','Bosque Emerald Ring',10,1,'item_standard',1,1750,'{}','A gold band with an extravagant bezel set Columbian emerald.'),
('provision_jewelry_french_dmnd_ring','Beaulieux Diamond Ring',10,1,'item_standard',1,1751,'{}','A number of old mine cut diamonds claw set in a silver ring from France.'),
('provision_jewelry_gld_bngle_bracelet','Ojeda Rose Gold Bangle Bracelet',10,1,'item_standard',1,1752,'{}','A large bracelet of rose gold with elaborate cameo detailing.'),
('provision_jewelry_gld_cross_necklace','Ainsworth Cross Necklace',10,1,'item_standard',1,1753,'{}','A solid gold chain necklace with an etched gold cross.'),
('provision_jewelry_gld_pearl_necklace','Rou Pearl Necklace',10,1,'item_standard',1,1754,'{}','A necklace made of fine rose gold featuring a single pearl from the Orient.'),
('provision_jewelry_gld_pendt_necklace','Gosselin White Gold Necklace',10,1,'item_standard',1,1755,'{}','A lavalier style white gold necklace with a series of small diamonds.'),
('provision_jewelry_grnet_bracelet','Hajnal Garnet Bangle Bracelet',10,1,'item_standard',1,1756,'{}','A bohemian style silver bangle with numerous claw set garnets.'),
('provision_jewelry_grnet_post_earring','Harford Garnet Earrings',10,1,'item_standard',1,1757,'{}','Clustered garnet studs with silver posts and scrolls.'),
('provision_jewelry_moon_ring','Pilgrim Moonstone Ring',10,1,'item_standard',1,1758,'{}','A thick gold band with a single claw set moonstone.'),
('provision_jewelry_mthr_pearl_necklace','Pellé Pearl Necklace',10,1,'item_standard',1,1759,'{}','A beaded chain necklace with a fashionable mother of pearl pendant.'),
('provision_jewelry_onyx_ring','Aubrey Onyx Ring',10,1,'item_standard',1,1760,'{}','A rare white gold ring with a bezel set diamond surrounded by polished onyx.'),
('provision_jewelry_pearl_bracelet','Durant Pearl Bracelet',10,1,'item_standard',1,1761,'{}','An intricate link bracelet with natural pearls and gold filigree.'),
('provision_jewelry_pearl_earring','Josephine Pearl Earrings',10,1,'item_standard',1,1762,'{}','Fashionable pearl earrings with neat gold hooks.'),
('provision_jewelry_pearl_ring','Bonnard Pearl Ring',10,1,'item_standard',1,1763,'{}','A valuable pearl set into a white gold band.'),
('provision_jewelry_pers_turq_ring','Thorburn Turquoise Ring',10,1,'item_standard',1,1764,'{}','A delicately crafted rose gold ring with turquoise beads.'),
('provision_jewelry_porcelain_necklace','Braxton Amethyst Necklace',10,1,'item_standard',1,1765,'{}','A fashionable necklace with a porcelain hand painted miniature.'),
('provision_jewelry_qn_dmnd_earring','Royal Victoria Diamond Earrings',10,1,'item_standard',1,1766,'{}','A series of small diamonds claw set in a floral cluster on a white gold band.'),
('provision_jewelry_rudy_dngl_earring','Beauchêne Ruby Earrings',10,1,'item_standard',1,1767,'{}','Elaborate gold hook earrings with vivid rubies.'),
('provision_jewelry_slvr_pearl_necklace','Silver Pearl Necklace',10,1,'item_standard',1,1768,'{}','A necklace made of fine silver and pearls.'),
('provision_jewelry_sphr_bngle_bracelet','Greco Sapphire Bracelet',10,1,'item_standard',1,1769,'{}','A delicate gold bracelet with three small sapphires.'),
('provision_jewelry_sphr_bracelet','Helena Sapphire Bracelet',10,1,'item_standard',1,1770,'{}','A fine silver bracelet with claw set sapphires.'),
('provision_jewelry_topaz_necklace','Dane Topaz Necklace',10,1,'item_standard',1,1771,'{}','A precious platinum chain necklace with a small drop of topaz.'),
('provision_jewelry_topaz_ring','Banais Topaz Ring',10,1,'item_standard',1,1772,'{}','A neat silver wedding ring with brilliant cut topaz.'),
('provision_jewelry_turquoise_bracelet','Infanta Turquoise Bracelet',10,1,'item_standard',1,1773,'{}','A solid silver bracelet with a large turquoise stone.'),
('provision_jewelry_turquoise_ring','Magnate Turquoise Ring',10,1,'item_standard',1,1774,'{}','A solid gold ring with an oval of polished turquoise from Persia.'),
('provision_jewelry_turq_stud_earring','Calumet Turquoise Earrings',10,1,'item_standard',1,1775,'{}','Lavish gold studs with claw set turquoise stones.'),
('provision_jewelry_whtgld_dmnd_ring','Sackville Diamond Ring',10,1,'item_standard',1,1776,'{}','A series of small diamonds claw set in a floral cluster on a white gold band.'),
('provision_jewelry_wht_dmnd_earring','Endicott Diamond Earrings',10,1,'item_standard',1,1777,'{}','Exquisite pendant earrings with old mine cut diamonds.'),
('provision_jewelry_ylwgld_dmnd_ring','Yates Diamond Ring',10,1,'item_standard',1,1778,'{}','An intricate gold band with one cushion cut diamond.'),
('provision_ring_platinum','Platinum Ring',10,1,'item_standard',1,1779,'{}','A finely crafted platinum ring.'),
('provision_ro_flower_acunas_star', 'Acunas Star Orchid', 10, 1, 'item_standard', 1, 1780, '{}', 'The Acunas Star Orchid an be identified by the branching of the stems, alternate leaves, and cream colored petals. The trailing plant is often found on the ground or growing around trees in swampland areas.'),
('provision_ro_flower_cigar', 'Cigar Orchid', 10, 1, 'item_standard', 1, 1781, '{}', 'The Cigar Orchid can be identified by the inflorescence which can produce around five hundred bright yellow flowers with purple and brown markings.'),
('provision_ro_flower_clamshell', 'Clamshell Orchid', 10, 1, 'item_standard', 1, 1782, '{}', 'The Clamshell Orchid can be identified by the deep purple and white petals with yellow streaks, and thin leaves.'),
('provision_ro_flower_dragons', 'Dragons Orchid', 10, 1, 'item_standard', 1, 1783, '{}', 'Dragons Mouth Orchids can be recognized by their wild purple flowers which are said to resemble a dragon. The general size of this type of orchid is around six inches.'),
('provision_ro_flower_ghost', 'Ghost Orchid', 10, 1, 'item_standard', 1, 1784, '{}', 'The Ghost Orchid is named after the white to pale pink flowers that can be seen in shaded habitats. This small orchid grows in shaded areas, such as woodlands, and under leaves and soil, with only the flower appearing above ground.'),
('provision_ro_flower_lady_of_night', 'Lady of Night Orchid', 10, 1, 'item_standard', 1, 1785, '{}', 'Lady of the Night Orchid takes its name from the sweet citrus fragrance it produces during nightfall. The orchid can be identified by the white heart shaped flowers and long leaves.'),
('provision_ro_flower_lady_slipper', 'Lady Slipper Orchid', 10, 1, 'item_standard', 1, 1786, '{}', 'Lady Slipper Orchid can be identified by the large bulbous purple flower and speckled purple leaves. This type of orchid can be seen growing in the ground of forests, meadows and woodland areas.'),
('provision_ro_flower_moccasin', 'Moccasin Orchid', 10, 1, 'item_standard', 1, 1787, '{}', 'Moccasin Flower Orchid can be identified by the yellow pouch like petal, red sepals, and wide leaves. This orchid can be found growing near pines or conifers in woodlands and forests.'),
('provision_ro_flower_night_scented', 'Night Scented Orchid', 10, 1, 'item_standard', 1, 1788, '{}', 'Night Scented Orchid can be identified by the alternate stems, the long sepals, and white petal flowers. This orchid can be found growing upon another plant, often draping down from trees.'),
('provision_ro_flower_queens', 'Queens Orchid', 10, 1, 'item_standard', 1, 1789, '{}', 'The Queens Orchid can be identified by the white sepals, and purple and white curled petal.'),
('provision_ro_flower_rat_tail', 'Rat Tail Orchid', 10, 1, 'item_standard', 1, 1790, '{}', 'The Rat Tail Orchid has long, thin hanging stems, pencil-like leaves and rigid flowering stems bearing up to twelve crowded white to cream-coloured flowers.'),
('provision_ro_flower_sparrows', 'Sparrows Orchid', 10, 1, 'item_standard', 1, 1791, '{}', 'The Sparrows Orchid usually has 3 to 7 oval or lance-shaped leaves arranged alternately on the stem.'),
('provision_ro_flower_spider', 'Spider Orchid', 10, 1, 'item_standard', 1, 1792, '{}', 'The Spider Orchid is Characterised by five long spreading petals and sepals around a broad down-curled lip.'),
('raisin','Raisin',10,1,'item_standard',1,1793,'{}','A dried grape that makes good eating.'),
('raw_bacon','Raw Bacon',10,1,'item_standard',1,1794,'{}','Raw uncooked bacon.'),
('sandbag','Sandbag',10,1,'item_standard',1,1795,'{}','A bag of sand. often used in construction.'),
('sandpaper','Sandpaper',10,1,'item_standard',1,1796,'{}','A sheet of sandpaper used for smoothing wood.'),
('spool','Spool',10,1,'item_standard',1,1797,'{}','A empty spool. often used to wrap wire around.'),
('string','String',10,1,'item_standard',1,1798,'{}','A bundle of string with many uses.'),
('teabag','Teabag',10,1,'item_standard',1,1799,'{}','A teabag for making that perfect cup.'),
('tealeaf','Tealeaf',10,1,'item_standard',1,1800,'{}','Used to make tea or teabags.'),
('timber','Timber',10,1,'item_standard',1,1801,'{}','A sturdy chunck of timber.'),
('vanillacake','Vanilla Cake',10,1,'item_standard',1,1802,'{}','A tasty vanilla flavored cake.'),
('varnish','Varnish',10,1,'item_standard',1,1803,'{}','A typical wood finish made from oils and resins.'),
('wedding_chain_ring','Wedding Ring on chain',10,1,'item_standard',1,1804,'{}','A wedding ring on chain. usally worn this way so they dont get lost.'),
('wedding_ring','Wedding Ring',10,1,'item_standard',1,1805,'{}','A beautiful wedding ring.'),
('wheat','Wheat',10,1,'item_standard',1,1806,'{}','Often ground up into flour to used in cooking and baking'),
('wheatseed','Wheat Seed',10,1,'item_standard',1,1807,'{}','When planted will grow into wheat.'),
('wicker','Wicker',10,1,'item_standard',1,1808,'{}','A natural material made from woven branches or reeds'),
('woodsaw','Woodsaw',10,1,'item_standard',1,1809,'{}','Used to cut wood.'),
('wood_plane','Wood Plane',10,1,'item_standard',1,1810,'{}','A wood plane used for shaping wood.'),
('wrench','Wrench',10,1,'item_standard',1,1811,'{}','A wrech used to tighten bolts and other things.');